### ISSUE TITLE
Provide option to open profile URL in web view.

### ISSUE THREAD

**Issue by davmillar** [mastodon/mastodon-ios#1003]
### Description

When following a remote user for the first time, their profile is often empty due to the way that ActivityPub and Mastodon function. There is no easy way to visit their profile in the iOS or iPadOS app as there is in the web application.

### Suggested Solution

Provide a way to access a user’s profile URL in a web view as a link with their username or URL as the text.

### Alternatives

It would be useful to display such a link in the empty timeline of the profile when the new follow case is in effect. However the feature ought to be accessible no matter the recency of the follow as there could be a variety of reasons for wanting to visit it: non-Mastodon post rendering unexpectedly, wanting to share it with a non-fediverse person, checking out their cool and exciting custom CSS, etc.

It may be adequate to have it as an option in the triple dot menu on the profile view, but it would feel hidden and difficult to discover. Perhaps paired with a link in the empty timeline placeholder message would be adequate?

### Additional Context

It may seem as though this is a speculative use case — why would you follow someone without seeing what they post already? In my case, I am following someone who followed me first, and am basing my follow primarily on their profile bio and the fact that they followed me first.

**Comment by Gargron** [comment]
An option like this exists on the share sheet.

**Comment by davmillar** [comment]
@Gargron thanks, I tried it and was able to open the profile as you suggested I would. I think I overlooked that option because I anticipated it being a way to share the page for their profile as my instance sees it, like the difference between sharing https://mastodon.social/@Gargron vs https://puz.fun/@Gargron@mastodon.social

Thanks again, appreciate your time and efforts.
