### ISSUE TITLE
[Feature]:  Easy login access

### ISSUE THREAD

**Issue by starboyvarun** [mastodon/mastodon-ios#1004]
### Description

I have just started using Mastodon ios. We need easy login access for Mastodon. If we want to use the application on multiple devices, writing passwords every time is tiresome. 

### Suggested Solution

We can use similar login practices as Google, Facebook etc.

**Comment by j-f1** [comment]
If you use a password manager, it should just be a matter of using Face ID / Touch ID to fill in the fields on the login screen. What specifically would be a faster way to log in?

**Comment by starboyvarun** [comment]
@j-f1  I am saying when we open application on new devices like laptops or iPhones or any other new device it's not very handy for the old it's fine.

**Comment by j-f1** [comment]
What is the simpler flow that you’re envisioning?

**Comment by starboyvarun** [comment]
Google One Tap is a feature that enables users to log in to websites and mobile applications using their Google accounts with just one tap, without the need to enter a username or password.

Here's a simplified flow for Google One Tap login process:

The user visits a website or mobile application that supports Google One Tap login.
The website or application requests access to the user's Google account information.
Google displays a prompt asking the user to grant or deny access to their Google account information.
If the user grants access, Google One Tap generates a unique token and sends it to the website or application.
The website or application uses the token to authenticate the user and log them in automatically.
The advantage of Google One Tap is that it simplifies the login process and eliminates the need for users to remember their usernames and passwords for each website or application they use. It also provides a secure way of authenticating users by leveraging Google's advanced security measures, such as two-factor authentication and machine learning-based anomaly detection.

Additionally, Google One Tap provides developers with a streamlined way to integrate Google login into their websites or applications, thereby reducing development time and complexity.

**Comment by j-f1** [comment]
Interesting! I don’t think that would work well for Mastodon, though. It would need to be adopted by every Mastodon server, and it would cause a decentralized social network to depend on a centralized authentication provider of some sort. Mastodon also already has “advanced security measures” including support for two factor authentication :)

**Comment by starboyvarun** [comment]
ok .
Mastodon doesn't have open timelines in the project section in GitHub.?
