### ISSUE TITLE
[BUG] Accessibility — display size

### ISSUE THREAD

**Issue by testuser51** [mastodon/mastodon-ios#1009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't see how many characters I have left to type
![111](https://user-images.githubusercontent.com/53906414/230963470-fc6bdcdf-8554-4176-baf0-26e73811341f.jpg)

### Expected Behavior

I see a number

### Steps To Reproduce

1. Open settings 
2. Display
3. Display zoom
4. Larger text
5. Open Mastodon
![999](https://user-images.githubusercontent.com/53906414/230967848-bfa6739b-a4cc-44a2-b9e5-75848b3f4033.png)

### Environment

```markdown
- Device: iPhone SE
- OS: iOS 16.4.1
- Version: v1.5.1
- Build: 303
```

**Comment by testuser51** [comment]
Could you please fix this as well? Same device and same steps to replicate the bug

https://mastodon.social/@newsblur/109405102640112155 

![IMG_1132](https://user-images.githubusercontent.com/53906414/235983819-b7c16a30-f607-4b8c-b636-8d291ee670c4.PNG)

**Comment by zeitschlag** [comment]
@testuser51 Great, that you found that, thank you :) I moved this to its own issue #1031
