### ISSUE TITLE
[Feature]: "open original page" option

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon-ios#1014]
### Description

On the web version of Mastodon, you can click on ⋯ for a post or profile and there's an option "Open original page" which shows the version of that post or profile on its original instance.

Can we have the same option in the official app please?

### Suggested Solution

All it would have to do at a technical level is open that post or profile's sharing link in the web browser. People can already do this manually (Share -> Copy -> paste into browser's address bar), this feature would automate the process.

Allowing people to have this option in the app would let them check to see if a profile really is blank, or if there is a more up to date version of a post thread, or see a non-Mastodon post in its original context.

**Comment by j-f1** [comment]
There should be a Share → Open in [Safari/Browser] option.

**Comment by zeitschlag** [comment]
Thank you for your feedback. As @j-f1 already has pointed out, it's there for both profiles and statuses:

<video src="https://user-images.githubusercontent.com/2580019/233735238-a236ecbf-4a1f-4515-9409-2a433f85c1b0.mp4"></video>

<video src="https://user-images.githubusercontent.com/2580019/233735250-261efbbf-f408-422e-b331-d4e8909b4a1f.mp4"></video>

<video src="https://user-images.githubusercontent.com/2580019/233735258-8789f049-c0a6-4bea-b6e1-c1988a88a91e.mp4"></video>

Does this solve the issue at hand @FediVideos? If so, feel free to close this issue :)
