### ISSUE TITLE
[BUG] Incorrect "Joined" date is displayed in the "About" Section

### ISSUE THREAD

**Issue by wolfBhuffn** [mastodon/mastodon-ios#1015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When tapping on "About", the joined date shown is incorrect.

![img_1575_720](https://user-images.githubusercontent.com/101427214/232175856-6d834319-05a9-4e81-8194-eee5fbbb05c3.jpg)

### Expected Behavior

When tapping on "About" the user should see the correct date that they joined.

### Steps To Reproduce

1. Launch app as a registered user
2. Tap on the Account Avatar [bottom-right corner] 
3. Tap "About" 

### Environment

```markdown
- Device: iPhone 12 Pro Max
- OS: iOS 16.3.1
- Version: 1.5.1
- Build: 303
```

### Anything else?

double checked in the API request. There is a mismatch in the data.

![screenshot_2023-04-14_at_9 17 59_pm_720](https://user-images.githubusercontent.com/101427214/232176212-87b186fa-27bd-49a1-b17d-2f158457fbef.png)

**Comment by j-f1** [comment]
That join date matches what I see on the web version: https://mastodon.social/@Kwame_wolfCrew. I think this should be moved to the main Mastodon repo to either respond with a full creation date/time or clarify that only the date component should be used.

**Comment by zeitschlag** [comment]
@wolfBhuffn Thank you for bringing this up. I just wanted to double-checked on my iPhone and it stated that you joined April 14th 2023, so everything worked as expected. But then I changed the timezone and boom, you joined a day earlier.

So, it's on us, unfortunately, and not on Mastodon 😂😭
