### ISSUE TITLE
[Feature]: Add greek for the ios app 

### ISSUE THREAD

**Issue by trlef19** [mastodon/mastodon-ios#1038]
### Description

No greek as an available language on crowdin

### Suggested Solution

Add greek as an available language on crowdin

**Comment by zeitschlag** [comment]
@trlef19 Thank you for bringing this up! I flipped the switch for [Greek in Crowdin](https://crowdin.com/project/mastodon-for-ios/el) for now and I assume we'll turn it on in iOS shortly. I'll keep you posted!
