### ISSUE TITLE
[Feature]: Add hashtags to a list

### ISSUE THREAD

**Issue by herr-schaft** [mastodon/mastodon-ios#1072]
### Description

Being able to follow a hashtag is a great feature. Would be even better if I could add them to a list.

### Suggested Solution

Allow for hashtags to be added to a list.
(With that: Show hashtags as well as people in the search to create/edit a list.)

**Comment by j-f1** [comment]
I think this would have to be implemented in Mastodon itself first.

**Comment by herr-schaft** [comment]
Yepp. Took a wrong turn in GitHub somewhere. Was already wondering why nobody had mentioned it. Thanks for the heads up
