### ISSUE TITLE
[Feature]: double tap should enlarge the photo, not copy the text

### ISSUE THREAD

**Issue by testuser51** [mastodon/mastodon-ios#1084]
### Description

I often enlarge photos. Double tap should enlarge the photo, not copy the text

https://github.com/mastodon/mastodon-ios/assets/53906414/6de836e1-f660-4ce5-b5d4-c9b6f9240b80

### Suggested Solution

Double tap to enlarge a photo, long tap to copy text

https://github.com/mastodon/mastodon-ios/assets/53906414/3d36f652-db1a-4839-8fc7-bfaac8334392

### Alternatives

Double tap to enlarge the photo, click on the icon in the lower right corner to copy the text. I think it was the solution of the Apollo app (for Reddit)

https://github.com/mastodon/mastodon-ios/assets/53906414/02e0de26-01ff-455e-81cd-de60cf0eb8ca

**Comment by zeitschlag** [comment]
Double-tap _does_ enlarge the photo — unless you double-tap on text, then the text is selected. This has been system behaviour since iOS 16, I think.

**Comment by testuser51** [comment]
You can compare the text selection after double-tapping in the gallery and in the app. The gallery allows you to double-tap on the text to enlarge the photo.

Maybe Apple made text selection less aggressive in new OS updates, I don't know.

I have iOS 16.5.1 and I see a difference between the gallery and the app

**Comment by zeitschlag** [comment]
Ah, I see, yeah, you're right, sorry!

**Comment by j-f1** [comment]
See #1089!
