### ISSUE TITLE
[BUG] <title> The “report an user” doesn’t work

### ISSUE THREAD

**Issue by evapavlik** [mastodon/mastodon-ios#1092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I want to report an user, in step 4 before sending I got the error message HTTP 404 not found and I can finish the report

### Expected Behavior

The report after step 4 is completed

### Environment

```markdown
- Device: iPhone 14
- OS: 16.5.1
- Version:
- Build:
```

**Comment by zeitschlag** [comment]
@evapavlik Thank you for reporting this. Can you please provide us with more detail (which server, which user, which version of the app, etc.)? Thank you.

**Comment by zeitschlag** [comment]
Will close this for now. Feel free to reopen it, if you have more information :)
