### ISSUE TITLE
[BUG] <title> App freezes when writing a toot

### ISSUE THREAD

**Issue by ElectricGiraffe** [mastodon/mastodon-ios#1096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I press on the poll button while trying to write a toot, the app freezes and none of the icons or the keyboard works

### Environment

```markdown
- Device: iPhone 12 mini
- OS: 16.5
- Version: 2023.11
- Build: 337
```

**Comment by whattherestimefor** [comment]
2024-12 includes several updates to the way posts are checked for validity while composing, which may resolve this issue. If you continue to experience this problem, please reopen.
