### ISSUE TITLE
[BUG] Allow users to unmask their password when typing it

### ISSUE THREAD

**Issue by joachim-n** [mastodon/mastodon-ios#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I type my password to log in, I can only see each letter for a few seconds.

This is bad UX, because users can't easily check for mistakes in their passwords. This means that users are less likely to use strong passwords which are long and complex to type with special characters.

Password fields should allow unmasking the password.

### Environment

```markdown
- Device:
- OS:
- Version:
- Build:
```

**Comment by zeitschlag** [comment]
Thank you for bringing this up.

We don't use a native form to let a user enter their credentials, we use the webinterface for that (together with [Authentication Services](https://developer.apple.com/documentation/authenticationservices)). So it isn't an issue of the iOS-app, that's why I'll close this issue here.

**Comment by joachim-n** [comment]
What is responsible for making the form?

**Comment by zeitschlag** [comment]
@joachim-n You do use a [password manager](https://en.wikipedia.org/wiki/Password_manager) and don't type in your password by hand, right? Then it wouldn't be necessary to check each character.

It's the same login form that you use when you log into the browser, so it's [Mastodon](https://github.com/mastodon/mastodon). But: As it's most probably standard HTML, it's Apple as they build Safari.

**Comment by joachim-n** [comment]
I use Firefox to manage my passwords, but it's not synced between devices, so I do need to type it into the Mastodon iOS app to log in there.
There seems to be some sort of problem, as no matter how many times I type it in, it doesn't log me in.
