### ISSUE TITLE
[Feature]: Support for the Apple Vision Pro/visionOS

### ISSUE THREAD

**Issue by upintheairsheep** [mastodon/mastodon-ios#1106]
### Description

The Apple Vision Pro and visionOS should have support for Mastodon. The Vision Pro lost hype because of it's initial price, although the first generation is really just a developer kit of sorts. The Apple developer documentation already has tutorials on how to create a visionOS version of the existing Mastodon iOS app with it's own UI and everything.

However, here are some concepts for inspiration:
https://twitter.com/BenGeskin/status/1670112830958305280
https://twitter.com/doganuraldesign/status/1667543080516329472
https://twitter.com/dribbble/status/1676612658454208514
https://9to5mac.com/2023/08/09/windows-xp-apple-vision-pro/

### Suggested Solution

NA

**Comment by zeitschlag** [comment]
Thank you for that suggestion. After a brief discussion we decided to focus our limited resources on things, that aren't an fancy gadget.

To be honest that is the kind of area that a healthy third party ecosystem like ours can help to serve. We want to focus on core product features for the broad majority of users, ideally adopting new platform features and best practices where we can, but leaving the niche and fancy use cases for others to prove out. So, in other words: Please feel free to give it a try!
