### ISSUE TITLE
[BUG/IMPROVEMENT] Can't edit alt-text in iOS 

### ISSUE THREAD

**Issue by murb** [mastodon/mastodon-ios#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently it is not possible to edit alt text in iOS

### Expected Behavior

Editing the post should allow for bringing up the edit interface for the alt text (and perhaps focal point, like in the web ui)

### Steps To Reproduce

1. Create a post
2. Forget to add alt-text
3. See some-one else suggesting alt-text
4. Can't add it to the image from iOS

(Mastodon server 4.2.1; latest iOS app)

### Environment

```markdown
- Device: iPhone XS
- OS: iOS 17
- Version: 2023.13
- Build: 348
```

**Comment by KreerC** [comment]
Thanks for the report! 

However, seeing that it is already three months old and unresponded to this day, I want to emphasize that it should be handled with utmost urgency. The bug prevents participation of blind users throughout the fediverse as overworked politicians or other content creators depend on it to make their content accessible to everyone, including blind users. To name an example for this: Anke  Domscheidt-Berg - https://social.linksfraktion.de/@ankedb/111789069091328497.

It would be great to see this fixed ASAP. Thank you.

**Comment by KreerC** [comment]
Thank you for fixing it _this_ quickly, very honourable! 💚
