### ISSUE TITLE
[Feature]: Please add Armenian language to Crowdin

### ISSUE THREAD

**Issue by tigransimonyan** [mastodon/mastodon-ios#1147]
### Description

name: Armenian (Հայերէն) 
code: hy

### Suggested Solution

We already have translations for the Web. So if possible, you can copy some translations before we start working on mobile.

**Comment by zeitschlag** [comment]
@tigransimonyan thank you for that suggestion. I just added Armenian to Crowdin: 

https://crowdin.com/project/mastodon-for-ios/hy-AM

(Crowdin just offered me `hy-AM`, but not `hy`)

Unfortunately, I'm not aware of any way to copy the existing translations from web to iOS, may I ask you to take care of this? Thank you :) Please feel free to open a PR adding Armenian as a language to the iOS-project (or just say something, then I'd take care of it.)

**Comment by tigransimonyan** [comment]
thanks ❤️
