### ISSUE TITLE
[BUG] Latest version crashes on startup

### ISSUE THREAD

**Issue by AquaBat** [mastodon/mastodon-ios#1160]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

After updating, the app crashes immediately when opened.

### Expected Behavior

The app functioning as normal on startup.

### Steps To Reproduce

1. Update to latest version
2. Go to app location
3. Tap to open app

### Environment

```markdown
- Device: iPhone 14
- OS: iOS 16.6
- Version: 2023.14
- Build: unknown (cannot open app to determine)
```

**Comment by zeitschlag** [comment]
@AquaBat Thanks for reporting. Of course this isn’t how it should be, I’m really sorry 🫠🫣

Can you share the crash-report with us as described [here](https://help.apple.com/xcode/mac/current/#/deve2819c518)? As an alternative, can you follow these steps (they're from [here](https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs#Locate-crash-reports-and-memory-logs-on-the-device) and post the crash report here?

> 1. Open the Analytics & Improvements section of Settings on the device. See [Share analytics, diagnostics, and usage information with Apple](https://support.apple.com/en-us/HT202100).
> 1. Tap Analytics Data.
> 1. Locate the log for your app. The log name starts with `<AppBinaryName>_<DateTime>` for crash reports, or `JetsamEvent_<DateTime>` for high-memory use crashes.
> 1. Select the desired log.
> 1. Tap the Share icon, and select Mail to send the crash report as a mail attachment.

In order to help we need a crash report. Thank you so much for you help and sorry for the inconvenience.

**Comment by AquaBat** [comment]
As much as I’d like to, it doesn’t seem to be generating a crash report at all. I checked the logs and nothing matches.
Maybe calling it a crash was premature, it seems more like the app simply refuses to open at all. It begins to fill the phone’s screen with a black background that would normally immediately be replaced with the app loading itself, but then stops and kicks the phone back to the Home Screen. The app isn’t visibly running in the background and can’t be selected on the App Switcher, it’s as if it never was selected at all. I could provide a video of it occurring but I’m concerned about the privacy of the apps on my Home Screen.

**Comment by zeitschlag** [comment]
@AquaBat Do you share the analytics with Apple and developers? If so, give us a day until they reach us.

Although it’s not a fix but more of a workaround: Have you re-installed the app?

I get that you’re concerned about your privacy, from your description it’s a crash. We don’t need a video, I believe you :) The question is: Where exactly does it happen on startup?

**Comment by yurkins** [comment]
@zeitschlag CrashLogs from iPhone XR, iOS 16.1.2
It was a clean install(not update), in the past mastodon was never installed on this device.
[Crashes.zip](https://github.com/mastodon/mastodon-ios/files/13362423/Crashes.zip)

**Comment by zeitschlag** [comment]
@yurkins Ah, great, thank you! This helps a lot.

**Comment by yurkins** [comment]
@zeitschlag  VisionKit -> ImageAnalysisInteractionDelegate -> **textSelectionDidChange(_:)** is available from **iOS 17+**

**Comment by zeitschlag** [comment]
@yurkins I know, thanks for pointing that out.

**Comment by verygenericname** [comment]
Broken for me on 16.1.2, too. I went here to make a bug report and saw this. Same crash too

**Comment by zeitschlag** [comment]
@verygenericname Thank you. @kimar is working on it and we'll ship a new release as soon as possible. I'm really sorry for that!

Nice first name, by the way^^

**Comment by mrickard** [comment]
@kimar I'm encountering this on an iPhone 14 (iOS 18.4.1 and 18.5) with the current version of the Mastodon iOS app. I do have .ips files for the crash, if you need them.

**Comment by mrickard** [comment]
Deleting and reinstalling the app mitigates this, so this issue can probably remain closed.
