### ISSUE TITLE
[BUG] When sharing article through share button in iOS, message “No available account”

### ISSUE THREAD

**Issue by ericderede** [mastodon/mastodon-ios#1168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to share an article from a news app and select Mastodon, I see the message No Available Account. This happens both in iOS and iPadOS. I tried reinstalling the app and logging out and in again.

![image](https://github.com/mastodon/mastodon-ios/assets/90373850/a2741985-d468-4eb6-8a6e-566f0639b3fb)

### Expected Behavior

When I share a article via a news app to the Mastodon app, I expect to see a title and a hyperlink, after which I can press Toot. The shared article should appear in my timeline.

### Steps To Reproduce

1. In a news app
2. Click the share icon
3. Choose Mastodon
4. A dialog appears with the text No Available Accounts 

### Environment

```markdown
- Device: iPhone 15/iPad 10
- OS: iOS/iPadOS
- Version: 17.0.3 
- Build: iOS/iPadOS 17.0.3 (21A360)
```

**Comment by briangmaddox** [comment]
I’ve had this exact issue for the past couple of releases.  Have tried uninstalling it on my iPhone and then reinstalling and same behavior.

**Comment by zeitschlag** [comment]
@ericderede @briangmaddox Thank you both for reporting it. I think/hope/guess When the weekend is over we'll merge it.

**Comment by TS6ix2GaH3q679h5** [comment]
Just here to say "same for me". I'm having the "no account available" error too.

**Comment by TS6ix2GaH3q679h5** [comment]
Confirming that 2023.16 fixes this issue for me! Thanks for the hard work folks.
