### ISSUE TITLE
[BUG] App crashes when trying to logout on iPad

### ISSUE THREAD

**Issue by stephensekula** [mastodon/mastodon-ios#1172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to manually logout of my account so I can start fresh, the app crashes. I am unable to log out of my account at all. I have also noticed that if I delete the app and reinstall it, all credentials are retained and I am not asked to log back into my account, which may not be the desired behaviour (in this case, I was hoping to be able to log back in fresh).

### Expected Behavior

Logging out of my account should not crash the app. I am also curious why deleting the app does not delete my account credentials. 

### Steps To Reproduce

1. Try to logout of account and log back in. 
2. Go to App Settings->Logout and the app crashes immediately. 

### Environment

```markdown
- Device: iPad Pro 5th Generation and iPad (6th generation)
- OS: 17.1.1 (Pro) and 17.1 (iPad)
- Version: v2023.15 (Pro) and v2023.14 (iPad)
- Build: 6005 (Pro) and 6001 (iPad)
```

### Anything else?

Server is a personal server hosted at home, mastodon.cooleysekula.net. No server side changed have occurred in a month. This problem began just in the last several days. I was able to share to app as recently as last week.

**Comment by stephensekula** [comment]
I will also note that what started this whole adventure in logging out was that I am unable to share to app from any other app (e.g. a browser, a news app). This seems to be related to bug #1168 , which I understand will be fixed in the next release. Perhaps all of the above is related to problems with accessing the keychain (e.g. deleting credentials when deleting the app, trying to logout and crashing, etc.)

**Comment by sercxanto** [comment]
Same problem here. iPad 6th generation with iOS 17.1.1.

The app crashes when I try to log out. The reason why I wanted log log out in first place, was that it doesnt show any new posts and shows a red „offline“ state. And yes, the server works perfectly with the web version and on Android.

What I wonder most: How is the app able to still be logged on even after re-installing it? Shouldn‘t iOS take care to delete the app data on uninstall? I dont use keychain at all, there are no credentials stored in it.

**Comment by zeitschlag** [comment]
> Shouldn‘t iOS take care to delete the app data on uninstall? I dont use keychain at all, there are no credentials stored in it.

Yes, there are credentials stored in there. We're not talking iCloud Keychain here, but the iOS-mechanism to encrypt and store secrets on your device. It's also called [Keychain](https://developer.apple.com/documentation/security/keychain_services).

iOS [doesn't clear the Keychain](https://apple.stackexchange.com/a/444912) just because you delete an app.

**Comment by vszakats** [comment]
Bumped into this. The reason I wanted to delete an account is because an experimental one I had added is offline, blocking the refresh (with a message "Offline") also for the rest of the accounts which are online (see #1178). This behavior came with a recent update (said account has been offline for a good while now, and it didn't block refresh globally until recently). Now, after logging out (it works without crashing in my case), the account reappears after each launch. Or even after deleting and reinstalling the app, like others have noted.

**Comment by zeitschlag** [comment]
You all use iPads, right? @vszakats @sercxanto @stephensekula

Do you see an alert or a share-sheet before the app crashes?

**Comment by vszakats** [comment]
Mine is seen on an iPhone. No crashes, the account is just back there after closing and re-launching the app. Edit: There is an "Are you sure you want to sign out?" confirmation popupping up fine.

**Comment by zeitschlag** [comment]
@vszakats This issue is for the crash. I noticed that you alteady opened a new one for your problem.

**Comment by stephensekula** [comment]
The crash happens with no warning or fanfare. The app simply disappears from view and must be restarted from its icon.

**Comment by vszakats** [comment]
@zeitschlag: I have two issues: 1. unable to logout from app (this issue, according to title) 2. the other one I opened which isn't about logging out.

Shall I open a new one for "unable to logout" but without a crash?

Edit: To add, the account in question is a self-hosted, experimental one. Logging out doesn't work either if the server is online or offline. Tried both with the same effect: logs out after confirming the popup, but the account is right there again, logged-in, after re-launch.

**Comment by sercxanto** [comment]
> You all use iPads, right? @vszakats @sercxanto @stephensekula
> 
> Do you see an alert or a share-sheet before the app crashes?

@zeitschlag I have an iPad 6th generation with iOS 17.1.1 and the same behaviour as described by @stephensekula : The app simply disappears without any prior windows popping up. I interpreted that as "crashing".

I don't know if this is related but on the top of the app there is a red status box showing "offline". I see my own post (made on another device), but my timeline is empty.

**Comment by zeitschlag** [comment]
@sercxanto Thank you! The crash is iPad-related, there's already a PR #1180 that fixes that.

The offline-banner is unrelated to the crash. But don't worry: We're looking into that one, too, as more people than before seem to be affected.
