### ISSUE TITLE
[BUG] Unable to logout from account

### ISSUE THREAD

**Issue by vszakats** [mastodon/mastodon-ios#1181]
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

After selecting an account, going "Logout <name>", and confirming this with a "Sign out" button, it seems to work (there is no crash), the account appears logged out (it's no longer in the selection list). But, when closing and re-launching the Mastodon app, the account is there again.

This happens regardless of the account being offline or online at the time of signing out.

Deleting the app and reinstalling it also doesn't resolve it, because all previous accounts re-appear automatically. This is odd in itself.

It means there is no way to remove an account from the Mastodon app.

### Expected Behavior

After sign-out the account disappears and never reappears until adding it back on manually.

### Steps To Reproduce

1. Start app.
2. Select an account.
3. Log-out from account.
4. Force close app.
5. Re-launch app.
6. Account is there again.

### Environment

```markdown
- Device: iPhone
- OS: 17
- Version: 2023.15
```

**Comment by kimar** [comment]
Thank you for reporting this. This is a bug which resulted from our recent credentials migration to the iOS keychain. Will be fixed in the next release.

**Comment by vszakats** [comment]
Thank you for the quick fix, I can confirm it working in 2023.16.

**Comment by davidhaller** [comment]
> Thank you for the quick fix, I can confirm it working in 2023.16.

I can confirm as well. Thanks a lot!
