### ISSUE TITLE
[Feature]: Search my posts by keywords

### ISSUE THREAD

**Issue by testuser51** [mastodon/mastodon-ios#1187]
### Description

Ability to search your posts by keywords

### Suggested Solution

1. Open your profile
2. Press 3 dots
3. "search by keywords"

### Alternatives

Add hints from the web version to the search field
![image](https://github.com/mastodon/mastodon-ios/assets/53906414/a1cedbf8-8b87-4cac-afb9-b78209891f1b)

But their problem is that it's unclear what the mastodon wants: a username, a username with a server, or a direct link to the profile (a bit confusing). Mastodon does not offer to automatically complete the field when you start typing

**Comment by zeitschlag** [comment]
@testuser51 When #1188 is merged you should be able to use the search options in the next release. So if you entered `from:testuser51` in the search field and press the `search`-button on the keyboard, you'd see your toots.

Does this solve your issue?

**Comment by testuser51** [comment]
It's not a perfect solution, but it's okay for now. 

But it would be nice if the search worked with alternative options:

- from:@testuser51
- from:@testuser51@server.name
- from:testuser51

**Comment by zeitschlag** [comment]
@testuser51 The app uses the same Search-API as the Web-app. So that should work.
