### ISSUE TITLE
Apple Silicone Issues

### ISSUE THREAD

**Issue by Modrx** [mastodon/mastodon-ios#1193]
Hi,

Apple Silicone M2
OS: Sonoma

When following the instructions as shown here:
https://github.com/mastodon/mastodon-ios/blob/develop/Documentation/Setup.md

After running the following command
```
echo 'eval "$(rbenv init -)"' >> ~/.zprofile
source ~/.zprofile
```

and then

`which ruby`

I am still getting:

`# > /usr/bin/ruby`

instead of 

`# > /Users/mainasuk/.rbenv/shims/ruby`

and unable to run

`rbenv install`

`bundle install`

Thank you!

**Comment by Modrx** [comment]
Hi,

The following is not working either:

```
echo 'eval "$(rbenv init -)"' >> ~/.zshrc
source ~/.zshrc
```

and then

`which ruby`

I am still getting:

`# > /usr/bin/ruby`

instead of 

`# > /Users/mainasuk/.rbenv/shims/ruby`

and unable to run

`rbenv install`

`bundle install`

Thank you!

**Comment by kimar** [comment]
@Modrx any chance you're not using Zsh ? Could you please post the output of `echo $SHELL` ? Thx!

**Comment by Modrx** [comment]
Output:

`/bin/zsh`

Still not working.

Thank you!

**Comment by kimar** [comment]
@Modrx sounds like something is off there with your setup, could you please follow the instructions for installing Rbenv in their documentation: https://github.com/rbenv/rbenv

**Comment by logicalmoody** [comment]
I have the same issue on the same platform. I am following the setup guide to a T

EDIT: I was able to get myself unstuck, posting the [solution](https://github.com/rbenv/rbenv/issues/1193#issuecomment-1863778532) here for @Modrx and others who end up here
