### ISSUE TITLE
[BUG] New posts fail to publish

### ISSUE THREAD

**Issue by trumf** [mastodon/mastodon-ios#1215]
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

Often when i try to publish a post it gets "eaten". I click publish and the app displays "publishing.." but will not resolve and actually publish the post. It gets stuck.

It might have to do with bad connection like https://github.com/mastodon/mastodon-ios/issues/846 but i havent noticed that i've been on particularly bad networks.

It might also have to do with posting links, since i anecdotally experience it more often when posting a link.

### Expected Behavior

I expect the post to published.

Alternativly it should show a "failed to post" message and save the message so i can try posting it again, Instead of needign to type it out once again.

### Steps To Reproduce

Obviusly really hard to reproduce since i guess it would have been caught in unit tests. 

1. in an environment with bad connection
2. try writing a post with a link
3. click publish and see if it is published.

### Environment

```markdown
- Device:iphone13
- OS:17.2.1
- Version:2023.16
- Build:6043
```

### Anything else?

server: mastodon.social

This is annoying enough for me to make a bug report about it, i often post on other apps just to avoid this issue (Ivory, zora)

**Comment by testuser51** [comment]
This is the biggest problem with this app. Unfortunately, it looks like no one is going to fix it

https://github.com/mastodon/mastodon-ios/pull/849

**Comment by whattherestimefor** [comment]
As of 2024-12, you should stay on the compose screen until the post publishes or fails to publish, which should allow you to avoid losing the typing work in most cases. Autosaving a draft post is a future feature.
