### ISSUE TITLE
Longer messages

### ISSUE THREAD

**Issue by Gypsiee** [mastodon/mastodon-ios#1226]
### Description

I want to be able to post longer and not with the limit that is currently set.  If I wanna post anything longer, I have to go to another application and SHAREit I would like to be able to post it directly. The limits are too limiting.

### Suggested Solution

Allow for longer post length

### Alternatives

None

**Comment by zeitschlag** [comment]
@Gypsiee Thanks for the issue. I just tried to reproduce your issue but wasn't able to. As you most probably know, the character limit for a status is configured by the server and not the app.

So, which instance/server are you on?

**Comment by zeitschlag** [comment]
Please feel free to reopen with more information :)
