### ISSUE TITLE
Replace "Reblog" with "Boost"

### ISSUE THREAD

**Issue by zeitschlag** [mastodon/mastodon-ios#1236]

**Comment by r10s** [comment]
+1, i was initially quite irritated by this "🔁 Alice boosted" vs "🔁 Alice reblogged" :) esp. as the posting as such seems not to be called "blogging"

**Comment by FediVideos** [comment]
Think this is a duplicate of https://github.com/mastodon/mastodon-ios/issues/632 ?

**Comment by zeitschlag** [comment]
Duplicate of #632 

Thank you @FediVideos
