### ISSUE TITLE
Crash when tapping the Profile-button too quickly

### ISSUE THREAD

**Issue by zeitschlag** [mastodon/mastodon-ios#1257]
## Steps to reproduce

1. Open app from cold start but with a logged in user (don't have an internet connection)
2. Tap on profile-tab immediately
3. Crash.

## Notes

- `var viewModel: ProfileViewModel!`
- `viewModel` requires an `authContext` and so it only exists when there's an `authContext`

## Possible Solutions

- Don't use Forced Unwrapping (make it either really optional or not at all)
- Block tapping on profile-tabs as long as the viewModel doesn't exist (could be weird)
- Use existing account stored on disk

**Comment by whattherestimefor** [comment]
This should be fixed in 2024.11
