### ISSUE TITLE
[BUG] People are able to block own domain

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon-ios#1269]
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

If you go to a profile on your own instance and click on ⋯ there is an option to block your own domain. This has caused havoc for a user who got in touch with FediTips, as they accidentally clicked on it.

### Expected Behavior

There shouldn't be an option to block your own domain. The web interface doesn't have this option, neither do third party apps.

### Steps To Reproduce

1. Go to a profile on same instance as you
2. Click ⋯
3. Observe option to block your own instance

### Environment

```markdown
- Device: Any
- OS: iOS
- Version:
- Build:
```

**Comment by zeitschlag** [comment]
Fixed in #1270 (just didn't close this issue)

**Comment by FediVideos** [comment]
Thank you for fixing this, just uploaded update! Brilliant work!
