### ISSUE TITLE
[BUG] 2024.4 release removed the ability to jump to latest post with a single tap

### ISSUE THREAD

**Issue by maspotts** [mastodon/mastodon-ios#1280]
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

Before the 2024.4 release one could jump to the most recent post by tapping on the header. After the 2024.4 release this no longer works. It is possible to jump to the latest post, but it takes two taps; once to open the new Following/Local menu and again to tap on the desired selection, but this is a lot less intuitive and a lot more fiddly than the single tap that was formerly required.  One can also tap on the “new posts” popup, but that only appears sporadically (presumably when new posts have actually showed up) so unless it is visible one is forced to use the new two-taps-on-the-menu method, which is very unsatisfactory.  I highly recommend either restoring the previous tap-on-the-header action or (better) provide a permanent button (next to the new menu) which triggers a jump to the top.

### Expected Behavior

There should be an easy way to jump to the top (the latest post) with a single tap.

### Steps To Reproduce

N/A

### Environment

```markdown
- Device: iPhone 15 Pro
- OS: iOS 17.4.1
- Version: 2024.4
- Build: 6325
```

**Comment by zeitschlag** [comment]
Thanks for reporting. Do you know that you still can tap on the StatusBar (the thing with the clock and the battery and WiFi and Cell-Signal, you know) to scroll to the top?
I hope this solves the issue at hand :)

**Comment by maspotts** [comment]
Thanks! no I hadn’t tried that because on my phone it’s mostly full of the dynamic island and touching that causes all all kinds of things to happen! I would recommend that you extend the touch zone to include the whole of the area all the way down to the pane that contains the actual posts, like it used to in the previous release. i.e. I should be able to touch the area to the right of the new Following menu.
