### ISSUE TITLE
[BUG] “Load missing posts” appears when there isn’t any

### ISSUE THREAD

**Issue by rrgeorge** [mastodon/mastodon-ios#1288]
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

The “load missing posts” timeline item appears when there is no posts between the old and new timelines. So tapping it just makes it disappear and connect the two timeline sections 

### Expected Behavior

For the button to not be present when it’s not necessary 

### Steps To Reproduce

1. Open the app after a short time
2. Wait for the timeline to load and show “load missing posts”
3. Tap “load missing posts”
4. Observe no posts are loaded and the timelines are now connected

### Environment

```markdown
- Device: iPhone 12 Pro
- OS: iOS 17.4.1
- Version: v2024.5
- Build: 6336
```

### Anything else?

https://github.com/mastodon/mastodon-ios/assets/8526392/cb04673c-27f8-45de-9d52-b320df0a8d22

**Comment by ghost** [comment]
Happening as well on my iPhone SE 2nd gen.

**Comment by renchap** [comment]
We are aware of this, and tracking it internally as IOS-275

Work is in progress to solve those timeline loading bugs.

**Comment by maspotts** [comment]
I hope you can also avoid showing it at all, unless there are a lot of missing posts: or even make it optional? It's a feature I've always found very intrusive and annoying in other social media apps. I much prefer to see all the posts directly and not have to click anywhere in order to see some arbitrary subset of posts.

**Comment by ghost** [comment]
> We are aware of this, and tracking it internally as [IOS-275](https://linear.app/mastodon/issue/IOS-275)

Thanks for the update! I always forget that you use an “internal” bug tracker as well. Just to be sure, there is no way to access this one, right? You don’t publish any roadmap or milestone?
