### ISSUE TITLE
[BUG] Polls don’t show choice after voting

### ISSUE THREAD

**Issue by rrgeorge** [mastodon/mastodon-ios#1289]
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

Polls don’t have choice marked after voting

### Expected Behavior

To have choice marked after voting

### Steps To Reproduce

1. Vote in a poll
2. Observe choice is not marked.

### Environment

```markdown
- Device:iPhone 12 pro
- OS: iOS 17.4.1
- Version: v2024.5
- Build: 6336
```

### Anything else?

![image](https://github.com/mastodon/mastodon-ios/assets/8526392/0c5d8fe9-e84c-4645-abcd-53d6193a8c95)
![image](https://github.com/mastodon/mastodon-ios/assets/8526392/eab29560-391f-4b47-84f3-230f525d60cd)

**Comment by kimar** [comment]
Thank you, I can confirm this is a state bug, looks like the selected item isn't correctly set when the data model is loaded.
