### ISSUE TITLE
[BUG] Crash or freeze when cutting text while making a post

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon-ios#1314]
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

When cutting text while making a post in a certain situation, the app becomes unresponsive.

### Expected Behavior

The text goes into my clipboard so I can close the app and try again.

### Steps To Reproduce

1. The environment seems to result from trying to add photos/gifs, then removing them while they are loading, which makes user interface less responsive
2. Copying text does not add it to your clipboard, and cutting text freezes the UI

### Environment

```markdown
- Device: iPad Pro 10.5" (maybe 1st or 2nd gen?)
- OS: 16.6.1
- Version: 2024.5
- Build: 6368
```

### Anything else?

This may be related to a bug which prevents images or GIFs from being added to your post.

**Comment by whattherestimefor** [comment]
2024-12 includes several updates to the way posts are checked for validity while composing, which may resolve this issue. If you continue to experience this problem, please reopen.
