### ISSUE TITLE
Every time I try to add images from my Akkoma , the app freezes

### ISSUE THREAD

**Issue by sallyFoster** [mastodon/mastodon-ios#1317]
My Akkoma is https://spectreofcommunism.boo, and every time I try to add an image, the app freezes in the image selection screen.

**Comment by kimar** [comment]
Potentially related to #1314 / #1315

**Comment by sallyFoster** [comment]
@kimar Where you guys able to fix the issues?

**Comment by whattherestimefor** [comment]
Can you confirm if your experience is similar to https://github.com/mastodon/mastodon-ios/issues/1315, or can you post a screenshot of where the app is frozen for you?

**Comment by sallyFoster** [comment]
@whattherestimefor The screen freezes. The keyboard becomes unresponsive. Everything just stops working.

**Comment by whattherestimefor** [comment]
2024-12 includes several updates to the way posts are checked for validity while composing, which may resolve this issue. If you continue to experience this problem, please reopen.
