### ISSUE TITLE
Newly supported languages (Hungarian)

### ISSUE THREAD

**Issue by oldman63** [mastodon/mastodon-ios#1344]
### Pitch

Hello everyone,

I am Gábor S. from Hungary.

6 months ago I initialized the translation of Mastodone for iOS into Hungarian, which is currently 71% complete (https://crowdin.com/project/mastodon-for-ios/hu).

My question is: how long will it take to get a new official Mastodone for iOS build with newly supported languages?

I am currently using version 2024.09 and iOS 18.0

Thx, Gabor

### Motivation

Expanding the supported languages

**Comment by whattherestimefor** [comment]
Thank you for contributing Hungarian!

I think I've managed to flip the correct switches so that you will see your Hungarian translations in our next release, 2024.11.

**Comment by whattherestimefor** [comment]
@oldman63, please check this in 2024.11 (should be releasing soon) and reopen if needed.  Thank you!
