### ISSUE TITLE
[BUG] Widgets don't show up when built using Xcode 16

### ISSUE THREAD

**Issue by kimar** [mastodon/mastodon-ios#1349]
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

When building the App using Xcode 16 any existing Widgets will be blank and new Widgets can't be added as Mastodon won't appear in the List of Widgets anymore.

### Expected Behavior

Widgets can be used and added.

### Steps To Reproduce

1. Checkout `develop`
2. Build and Run on a device or simulator using Xcode 16

### Environment

```markdown
- Device: iPhone 16 Pro Max
- OS: iOS 18.0.1
- Version: 2024.10
- Build: -
```

### Anything else?

When running the `WidgetExtension` scheme the run times out and produces this error message:

![Bildschirmfoto 2024-10-10 um 14 09 43](https://github.com/user-attachments/assets/971c7e6f-f484-41ef-b39a-2fc5e28c8b78)

Additionally the Console.app yields the following error:

```
Content load failed: unable to find or unarchive file for key: [org.joinmastodon.app::org.joinmastodon.app.WidgetExtension:Hashtag:systemMedium:8711387500746600328:370.67/176.67/23.00:(null)] on no host. The session may still produce one shortly. Error: Using url `file:///private/var/mobile/Containers/Data/PluginKitPlugin/3B2C6C4B-E3ED-40C0-A22A-ED57C702141E/SystemData/com.apple.chrono/timelines/Hashtag/systemMedium--8711387500746600328----370.67w--176.67h--23.00r--1f--0.00t-0.00l-0.00b0.00t.chrono-timeline` ... WidgetKit.WidgetArchiver.ValidationError.bundleStubNotSupported(underlyingError: ChronoKit.(unknown context at $1dcfa1844).SimpleError.message("Bundle could not be looked up"))
```

**Comment by renchap** [comment]
I reported this issue after seeing it in our internal Testflight build but… now the widgets are working fine? They were blank, but now I am able to add new widgets or edit their settings.

I am not sure what changed here, but it must not be specific to my device if you are able to reproduce in the simulator, maybe this will help figuring out what is happening.
