### ISSUE TITLE
[BUG] Mastodon iOS App Ignores "Hide completely" Filter action Setting

### ISSUE THREAD

**Issue by Diwannist** [mastodon/mastodon-ios#1354]
### Is there an existing issue for this?

- [x] I have searched the issues (both open and closed)

### Current Behavior

Posts containing filtered words still appear in the feed with a "Filtered" label, indicating that the Hide completely setting from the web is not being respected by the iOS app.

### Expected Behavior

Content containing filtered words should be hidden entirely on the iOS app.

### Steps To Reproduce

1. Open Mastodon on the web.
2. Go to Preferences > Filters > Add new filter.
3. In the Title field, add a title for your filter.
4. Under Filter contexts, select Home and lists.
5. In Filter action, choose Hide completely.
6. In Keyword or phrase, enter a.
7. Click Save new filter.
8. On an iPhone 13 Pro Max, open the official Mastodon iOS app.
9. Scroll through your Home feed.

### Environment

```markdown
- Device: iPhone 13 Pro Max
- OS: iOS 18.1
- Version: 2024.10
- Build: 6834
```

**Comment by whattherestimefor** [comment]
https://docs.joinmastodon.org/methods/filters/#create

**Comment by Diwannist** [comment]
Thank you for your swift response. Can we ask why you linked to an API method? Please, excuse our ignorance and congratulations on joining the Mastodon team as we saw in a recent Mastodon blog post.

**Comment by whattherestimefor** [comment]
> Thank you for your swift response. Can we ask why you linked to an API method? Please, excuse our ignorance and congratulations on joining the Mastodon team as we saw in a recent Mastodon blog post.

Was just making a note to myself. :)  The iOS app's concept of a filter doesn't yet include the concept of filter_action.

Working on this one, hopefully you'll see a fix soon.

**Comment by Diwannist** [comment]
@whattherestimefor That was some great work. The improvement from a "Filtered" label to the user's chosen filter name is noticed.

The Mastodon iOS app still ignores Filter action > Hide completely. Do you see this behavior?

**Comment by whattherestimefor** [comment]
@computerstimulation Haven't confirmed myself yet, but have an additional report https://github.com/mastodon/mastodon-ios/issues/441#issuecomment-2533962106

Reopening this one for now.

Thanks!
