### ISSUE TITLE
[BUG] stuck in login popup on iPad

### ISSUE THREAD

**Issue by kdekooter** [mastodon/mastodon-ios#1375]
### Is there an existing issue for this?

- [x] I have searched the issues (both open and closed)

### Current Behavior

On the first run of the iPad app a (browser?) modal popup appears. After successfully login the mastodon web app is shown in this popup. But there is no way to get out of it. Except by cancelling the modal popup.

![Image](https://github.com/user-attachments/assets/2e8c0cec-47a5-437b-80d8-815c849a0060)

### Expected Behavior

Have some way to break out of this dialog and use the app.

### Environment

```markdown
- Device:
- OS:
- Version:
- Build:
```

**Comment by whattherestimefor** [comment]
I have seen this occasionally when running in the debugger with breakpoints on in the authentication process.  But I haven't yet been able to reproduce it in the shipping app, even with a very poor network connection.

@kdekooter Is this a persistent problem for you?

**Comment by kdekooter** [comment]
It is working now, thanks.
