### ISSUE TITLE
[BUG] Not open Profile view when tapped Author name in home feed

### ISSUE THREAD

**Issue by gokulvenkat243** [mastodon/mastodon-ios#1379]
### Is there an existing issue for this?

- [x] I have searched the issues (both open and closed)

### Current Behavior

- Showing post details when I tapped author name

### Expected Behavior

- Show profile view when tapped author name

### Steps To Reproduce

1. Goto home feed
2. Tap author name
3. showing post details instead of profile view

### Environment

```markdown
- Device: iPhone16 Pro
- OS: iOS 18.1
- Version: 2024.12
- Build: ?
```

**Comment by whattherestimefor** [comment]
Fixed by https://github.com/mastodon/mastodon-ios/commit/e4214f78a5fcc250ed25e0509d095ba97760025b
