### ISSUE TITLE
Update visibility menu appearance in the compose scene

### ISSUE THREAD

**Issue by MainasuK** [mastodon/mastodon-ios#144]
Remove the "Unlisted" option for the visibility menu. And add the checkmark for the current selection.

**Comment by ShadowJonathan** [comment]
Why was this removed?

**Comment by DraconicNEO** [comment]
> Why was this removed?

Probably some dumb idea about unlisted posts going away which ultimately didn't come to fruition. One of us should start working on the PR to add it back since it's clearly needed.
