### ISSUE TITLE
Manage multiple accounts

### ISSUE THREAD

**Issue by Tealk** [mastodon/mastodon-ios#220]
Hello,

it would be great if there would be a function to manage multiple accounts and switch between them.

Especially as an administrator you could benefit from it, know some instances that distribute news about the instance via a separate account.

**Comment by ShadowJonathan** [comment]
Telegram implements this pretty neatly by allowing you to long-press the "user icon" in the bottom right, like so;

![image](https://user-images.githubusercontent.com/22740616/127785124-fc034d72-f967-40b6-af2f-28e05f1f6f9f.jpeg)

(Censored for privacy reasons, it shows the name and avatar of the other account)

Maybe such a long-press action could be added to quickly allow switching? There on telegram, a user can hover their finger over the new account and then release to quickly complete that action.

**Comment by OddHouseGames** [comment]
Account switching would be great, I was looking for that this morning.

**Comment by MainasuK** [comment]
The multiple accounts works in v1.2.0 (88) now.
