### ISSUE TITLE
It's very tiny on my iPad Mini 5

### ISSUE THREAD

**Issue by kyefox** [mastodon/mastodon-ios#224]
I'm not an iWhatzit dev, so this might be the expected behavior for an app not explicitly made for iPads.

![IMG_0048](https://user-images.githubusercontent.com/27457339/127724028-d8fe7080-9bd2-4b5e-ac54-982b36ab626a.PNG)

The expander will make it grow to fill most of the vertical width, but still leaves a lot of room on the sides.

**Comment by Gargron** [comment]
This is normal for apps not made explicitly for the iPad

**Comment by ShadowJonathan** [comment]
Are there any plans to accommodate an ipad interface?

**Comment by Gargron** [comment]
In the future but it requires more design work

**Comment by zeitschlag** [comment]
We support iPads now.
