### ISSUE TITLE
Text cut off when iOS set to zoomed mode

### ISSUE THREAD

**Issue by OddHouseGames** [mastodon/mastodon-ios#225]
![image](https://user-images.githubusercontent.com/62911518/127737246-0a95a3e8-4801-4fc7-804e-941a17ddd52e.jpeg)

The new iOS app works great in zoomed except for a few areas:

the followed section is cut off on the right 
![image](https://user-images.githubusercontent.com/62911518/127737223-31985b28-fdd8-49ff-a982-00cae1d519ce.jpeg)
and the profile following/followers section![image](https://user-images.githubusercontent.com/62911518/127737229-79d15a45-0bb1-48ec-8b2a-38034212c444.jpeg)
The 'see all' text on the recommended profiles screen![image](https://user-images.githubusercontent.com/62911518/127737403-bb33814e-4c97-4027-83a2-e06856cedc15.jpeg)

You can also see the following button text is too close to the edges of the button here

![image](https://user-images.githubusercontent.com/62911518/128167818-46e1c4f5-36e9-4ee3-9162-f4d8d7213dfb.jpeg)

**Comment by OddHouseGames** [comment]
Looks like as of today these are all fixed except for the tight spacing here on the search page  ![image](https://user-images.githubusercontent.com/62911518/128276440-467e7b5b-d3c1-4912-942a-ee11bf137bef.jpeg)

**Comment by MainasuK** [comment]
Oh. I see.

**Comment by MainasuK** [comment]
Fixed in v1.0.3 (53). 
Thank you for your feedback.

**Comment by OddHouseGames** [comment]
Last zoomed issue seems to be when users follow you, it's hard to tell what is happening with text cut off![image](https://user-images.githubusercontent.com/62911518/128613493-75193a25-9090-4727-89ad-721355afcfcc.jpeg)
