### ISSUE TITLE
Add a sentence from bio in ‘accounts you may like section) Feature Request

### ISSUE THREAD

**Issue by OddHouseGames** [mastodon/mastodon-ios#226]
In the 'accounts you may like section/find people to follow' it would be a lot more useful if it pulls a sentence from the bio to provide context instead of having to go in one by one to see what they are all about.

Also, what is the horizontal row at the top of the 'see all' page?
![image](https://user-images.githubusercontent.com/62911518/127737344-771501b6-b906-4b02-92fa-900f372b217a.jpeg)

![image](https://user-images.githubusercontent.com/62911518/127737349-1b697ad4-2bef-4c1e-988f-538c0b162440.jpeg)

**Comment by zeitschlag** [comment]
Obsolete due to #1044
