### ISSUE TITLE
Add feedback button or link to Git Repository in iOS app settings menu (Feature Request)

### ISSUE THREAD

**Issue by OddHouseGames** [mastodon/mastodon-ios#228]
It would be great user experience to have a feedback button in the new iOS app or at least a link to the Git repo for easy reporting.

**Comment by Gargron** [comment]
We might not be able to link to the GitHub repository from the app if the GitHub page in any way mentions that you can donate to the development, as Apple requires that to go through their IAP system.

**Comment by zeitschlag** [comment]
It's there.
