### ISSUE TITLE
Tiny globe and 2 styles of eye icons needs clarification

### ISSUE THREAD

**Issue by OddHouseGames** [mastodon/mastodon-ios#231]
The globe icon seems impossibly small in the iOS app![image](https://user-images.githubusercontent.com/62911518/127737884-65ef55cb-4055-4004-8d19-22de05df8866.jpeg)

Also why is it sometimes an eye and sometimes a globe, aren't those two separate functions?

One is referring to timeline and one is visibility. What if a post is both?

Actually there seems to be two types of eyes, the small grey one like the globe and then the large blue one.
![image](https://user-images.githubusercontent.com/62911518/127737994-7ded2819-fbb7-4556-b149-b0b92e22eb1f.jpeg)![image](https://user-images.githubusercontent.com/62911518/127737997-a28fb161-41be-4e66-831f-4c986c397220.jpeg)
What is the differentiation for the user experience here?

Just trying to understand what a user is supposed to get from the tiny globe, and the two different styles of eyes.

**Comment by MainasuK** [comment]
The globe is means post visibility is `public`. The "eye with a slash" is means `unlist`. 
The icon is the same as the compose toolbar visibility menu icons. But that toolbar is omitting `unlist` on purpose.

Also, the visibility icon is set hidden when the post needs a content warning toggle button. Sorry for the confusion. Maybe there will a patch for that in the future.

**Comment by OddHouseGames** [comment]
Got it, thanks for clarification!
