### ISSUE TITLE
DM Scope not copied when replying

### ISSUE THREAD

**Issue by mstdn** [mastodon/mastodon-ios#232]
Meow all! I have been searching but don't think this is open yet:

When you reply on a DM within the app the Direct scope does not get copied and the reply will be public. 

- Reply should copy the original post scope

Well, that's it! :)

**Comment by ShadowJonathan** [comment]
+1, got the same issue here, accidentally published some semi-sensitive information to the global timeline before removing it.

**Comment by weex** [comment]
I don't see any labels here but I'd attach a priority:high or critical since it may expose private information.

**Comment by MainasuK** [comment]
The app should set visibility for DM in v1.0.1 (51) now.
