### ISSUE TITLE
Users will be registered in English or Arabic even if they are using other languages

### ISSUE THREAD

**Issue by noellabo** [mastodon/mastodon-ios#238]
# Expected behaviour

When users register from Mastodon for iPhone, they will be registered in the language supported by the server in the 'preferred language order' of the iOS preferences.

# Actual behaviour

When registering as a user on Mastodon for iPhone, the language used will be either English or Arabic. If you are not using Arabic, the language will be English.

Since you are getting `Locale.current.languageCode`, only languages that the app already supports localization will be selected.
https://github.com/mastodon/mastodon-ios/blob/b5263889bf2a015e2ba7a6330971e1c2da803801/Mastodon/Scene/Onboarding/Register/MastodonRegisterViewController.swift#L753

# Specifications

Users who do not use English and Arabic will fall back to English, even if they use a language supported by Mastodon. This is not the expected behavior.

What happens to users who are not using English or Arabic

- The user will be assumed to be an English speaker
- Emails to confirm email will be sent in English.
- The welcome message email is sent in English
- 'Find People to Follow' will show users who use English first.

Well, it's not a big problem that the emails are sent in English. However, it is a very bad experience when a user whose language you don't use is given priority in the first important follow candidate after registration.

You should get the list of languages supported by Mastodon (it is not provided, so you need to hardcode it) and select the appropriate one from the languages specified in `Locale.preferredLanguages`.

**Comment by noellabo** [comment]
Since my Mastodon server, which is mainly Japanese, does not work as expected in almost all cases, I decided to ignore `locale` and enforce `ja` for user registration by API from the app.

**Comment by noellabo** [comment]
I have confirmed that the problem has been resolved. thank you!

**Comment by MainasuK** [comment]
The app set the first preferred local in v1.0.1 (51) now.

I do not check the server language codes (or hard-coded i18n list). Because the second fallback language code may not make sense due to most people only have one native language. The second preferred language may surprise users, and also can not guarantee users can read it. For example, I just set a second language for font glyph fallback. And this patch should work for most users.

Finally. Thank you for your feedback.
