### ISSUE TITLE
Add footer in settings with feedback, version, and repo

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon-ios#243]
It'd be useful to have a footer in the Settings menu that shows;
- [ ] Where to file bugs (this issue tracker)
- [x] The open-source repo (it could be argued the license calls for that, but i think it should be possible to open the original source from the app anyways)
- [x] The version number, for debugging and dev purposes.

**Comment by MainasuK** [comment]
The GitHub link to this repo and app version footer should display in v1.0.1 (51) now.
