### ISSUE TITLE
Implement lists

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon-ios#246]
Related to https://github.com/mastodon/mastodon-ios/issues/227

Other iOS mastodon apps like Toot! implement lists, same as the mastodon web client.

**Comment by OddHouseGames** [comment]
+1 for lists

**Comment by ShredderWalnut** [comment]
Seconded. I just started taking advantage of the Lists feature in the web interface, and was surprised to find out it's unavailable yet in the mobile apps.

**Comment by Gargron** [comment]
It's planned

**Comment by daixtrose** [comment]
> It's planned

When? #NoEstimates

**Comment by tomfinitely** [comment]
As more diaspora migrations occur, I suspect this is going to be a HUGE feature request since it was pretty seamless a process Over There 🐦

**Comment by bmalbuck** [comment]
Just came across this problem today. Would love to look into it if not already scoped and assigned. Thinking a long tap on Home tabbar button pops up a list of your Lists along with Home option to remove list filter.

Other ideas?

**Comment by j-f1** [comment]
I like the Twitter approach of multiple top tabs on the home tab that you can swipe between! (Plus a way to view all of your lists somewhere else)

**Comment by rrgeorge** [comment]
A great way to implement lists would be to add them to this new dropdown menu:
![image](https://github.com/mastodon/mastodon-ios/assets/8526392/9b1a1e8e-726a-4a80-adcd-ba8e1d9fb85b)

**Comment by brendanjones** [comment]
Isn’t this already complete?

![Image](https://github.com/user-attachments/assets/2b74c3e4-0636-455b-a109-04ed9f5468e8)

**Comment by whattherestimefor** [comment]
They are viewable, but cannot be created or edited. That feature is covered by https://github.com/mastodon/mastodon-ios/issues/693
