### ISSUE TITLE
Some tactile feedback nits

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon-ios#248]
- [ ] Maybe a micro animation should play when you tap fav/boost that corresponds to the tactile function, right now the animation is "mute", while the tactile feedback is a small delayed "ka...chunk" feel
- [ ] Disable the tactile feedback (or make it a single feedback tap) when un-favving a post, right now it has the same vibration.
- Change up the vibration? The delayed ka-chunk doesn't feel quick and snappy to me, or maybe not "quick enough"

**Comment by MainasuK** [comment]
The first haptic feedback is trigger when tapping. And the second will be notified "Success" or "Failure" with different haptic styles. 

I can update it if any explicit UX design description for these interacts.

**Comment by MainasuK** [comment]
The haptic feedback is updated in v1.0.3 (53).

**Comment by MainasuK** [comment]
The haptic feedback was updated for UX design. Will release in v1.2.0.
