### ISSUE TITLE
Long-press context menus

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon-ios#249]
Right now, the three-dot context menu feels "claustrophobic", very close to the button that spawned it (it doesnt spawn at the margins of the tap area).

Additionally, the context menu feels "wrong" with theme and feel in comparison to the other theming of the app.

Instead; could it be done so that a context menu is behind a long-press? Twitter does this (in addition to a non-claustrophobic context menu), and the functionality provided in the long-press context menu is sorta alike to the functionality offered in the current context menu (mainly about blocking and muting)

**Comment by thadguidry** [comment]
Can be closed now.
The ellipses (3 dot) context menu on posts next to authors name is now a long press (held for more than 1 second)
