### ISSUE TITLE
Re-add the "unlisted" visibility option

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon-ios#250]
Apparently this was removed as per https://github.com/mastodon/mastodon-ios/issues/144, why? It's a completely valid visibility option for mastodon, all apps (web or mobile) support it.

**Comment by MainasuK** [comment]
related #231

**Comment by MainasuK** [comment]
@Gargron It seems to cause some confusion after removing the `unlist` option for the visibility menu.

**Comment by ShadowJonathan** [comment]
It's not confusing that #231 exists, that is just a consequence of removing the "unlisted" visibility option, while it is a completely valid approach.

It is still supported on the web client, it is supported on all other mobile clients, why is it not supported here?

**Comment by brookmiles** [comment]
Rather confusing that this useful post option is missing from the iOS client (for no apparent reason?) when it is present on the web client.

**Comment by jollheef** [comment]
@MainasuK 
> related #231
> But that toolbar is omitting unlist on purpose.

What was the purpose?

**Comment by anubis-666** [comment]
Please enable the unlisted toot.  It is a important method of posting when you want to be more public but don’t want to pollute the local timeline.

**Comment by reallyjat** [comment]
This is useful for doing threads on Mastodon as you can make the first post public and then replies can be unlisted to keep the timeline less polluted.

**Comment by reallyjat** [comment]
It looks like the code for unlisted is present but just commented out… can it be reinstated?

**Comment by hedgefield** [comment]
Yes please. Same question is being raised on the android repo. A strange choice to remove a feature that is still available on the web and in other third-party apps. https://github.com/mastodon/mastodon-android/pull/103

**Comment by jmeosbn** [comment]
> This is useful for doing threads on Mastodon as you can make the first post public and then replies can be unlisted to keep the timeline less polluted.

I also read that this was the preferred practice.

Wanting to be a polite user, I was confused this option was missing here, but present on the web and the other apps I’ve just checked.

As an alternative, I tried setting the post to followers only (I assume people will still see the replies to the original post), but this prevents reposting.

**Comment by FediVideos** [comment]
Just saw new people replying on FediTips confused by the lack of unlisted option. It would make sense to restore this option, especially as they see existing users advising them to use this option when posting replies.

**Comment by outfrost** [comment]
It seems that feature parity with the web UX, including (re-)adding missing features such as unlisted posting, has pretty unanimous support in the community, except for @mastodon's UX designer. Is there a reason why design direction hasn't been adjusted?

See also: mastodon/mastodon-android#37, mastodon/mastodon-android#103

**Comment by Cassolotl** [comment]
This is now essential in light of *https://github.com/mastodon/mastodon/pull/26344*, which will make all public posts from "discoverable" accounts searchable.

**Comment by DraconicNEO** [comment]
Seriously this is still an issue more than 2 years later? Why? It's clear unlisted posts aren't going away any time soon, why not add them back into the app. The way it is currently is just not good since any replies to posts appear in the timeline as public and not unlisted as replies should.
