### ISSUE TITLE
Crash & unforeseen response in timeline and personal page view

### ISSUE THREAD

**Issue by martin-cao** [mastodon/mastodon-ios#255]
I don't know where I tapped, maybe the navigation bar or status bar at the timeline view. As I tapped it, the app crashed, and i can't fix the issue, even reinstalling.
Also the icons in the tab bar is not at centre vertically. I don't know for sure but it might need to create a custom tab bar to fix the issue.

**Comment by MainasuK** [comment]
Could you describe the OS version, device type, and make a screenshot for that? Thanks.

**Comment by martin-cao** [comment]
The crash reproduction is down below:
> https://user-images.githubusercontent.com/54637858/127953112-98bbea30-ad1b-4eae-a714-2ea009563915.MP4

This is an **iPhone SE (2nd gen)** running **iOS 15 Developer beta 4** (19A5307G) (the latest version).

**Comment by martin-cao** [comment]
I don't know what happened, but the issue is fixed now.

**Comment by martin-cao** [comment]
New issue:
It can be opened now, but as I scroll down in the scroll view, it crashes. Maybe it's caused by the same reason.
https://user-images.githubusercontent.com/54637858/127954983-b7479f8d-c8c9-43fe-8b6b-fa73f1c7a306.MOV

**Comment by martin-cao** [comment]
Issue follow-up:
I tried another account on another instance, it couldn't fetch previous posts.
Same issue on another iPhone XR running on iOS 14.6

https://user-images.githubusercontent.com/54637858/128026057-e0fec8f2-c4fe-4f07-894d-db1d1f68123e.mov

**Comment by martin-cao** [comment]
I checked the iPhone's control panel, there are some errors.

>错误	22:00:20.392595+0800	Mastodon	Couldn't read values in CFPrefsPlistSource<0x282e20800> (Domain: group.org.joinmastodon.app, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd

>错误	22:00:20.547682+0800	Mastodon	Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <Mastodon.ControlContainableTableView: 0x10204b800; baseClass = UITableView; frame = (-187.5 -333.5; 375 667); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x280e7b9f0>; layer = <CALayer: 0x28004ca60>; contentOffset: {0, 0}; contentSize: {375, 0}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <_TtGC5UIKit29UITableViewDiffableDataSourceO8Mastodon13StatusSectionOS1_4Item_: 0x280210de0>>

>错误	22:00:20.681910+0800	Mastodon	Called -[UIContextMenuInteraction updateVisibleMenuWithBlock:] while no context menu is visible. This won't do anything.

>错误	22:00:23.395128+0800	Mastodon	    AVAudioSession_iOS.mm:1244  Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

>错误	22:00:45.579034+0800	Mastodon	Task <C3C34E4B-B794-4559-8DE0-5E0AFE70DF1B>.<12> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x280f8ec40 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=4}

>错误	22:00:51.663469+0800	Mastodon	Unknown client: Mastodon

>错误	22:01:03.135179+0800	Mastodon	AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:543 (
	0   AXRuntime                           0x00000001a6cedcf8 CBB94D3F-E9D0-307F-93FF-4086A92DA64A + 322808
	1   AXRuntime                           0x00000001a6ca382c _AXGetPortFromCache + 708
	2   AXRuntime                           0x00000001a6ca4f3c AXUIElementPerformFencedActionWithValue + 488
	3   UIKit                               0x00000001f0d11358 FE4B7226-5537-3AB1-9F46-93E4A91E2199 + 926552
	4   libdispatch.dylib                   0x0000000180d8c7ac EFF718CD-15A4-32CF-BD42-FE6D704D97DC + 10156
	5   libdispatch.dylib                   0x0000000180d8e518 EFF718CD-15A4-32CF-BD42-FE6D704D97DC + 17688
	6   libdispatch.dylib                   0x0000000180d95da4 EFF718CD-15A4-32CF-BD42-FE6D704D97DC + 48548
	7   libdispatch.dylib                   0x0000000180d96920 EFF718CD-15A4-32CF-BD42-FE6D704D97DC + 51488
	8   libdispatch.dylib                   0x0000000180da11b4 EFF718CD-15A4-32CF-BD42-FE6D704D97DC + 94644
	9   libsystem_p

(“错误” means "error")

One of the errors (Called... something) is repeatedly occurring.

I found that when I use the account at [mast.dragon-fly.club](mast.dragon-fly.club), it will crash in the timeline view as I scrolled to one specific post. I tried to reproduce this on 2 other accounts at [mastodon.social](mastodon.social) & [mastodon.online](mastodon.online). As I scrolled down to the bottom it shows as the circumstance in the previous comment (stopped at some posts around 1w ago (it shows that)). Then I checked that guy's personal page, it doesn't show the previous posts when I scrolled to the bottom.

**Comment by Gargron** [comment]
It sounds like a specific post is crashing it. Do you have any idea which post it might be?

**Comment by martin-cao** [comment]
> It sounds like a specific post is crashing it. Do you have any idea which post it might be?

I'm not quite sure, but it might be this post: https://monado.ren/@oldbag_bot/106691549307314454

**Comment by MainasuK** [comment]
Fixed in v1.0.3 (53). 
Thank you for your feedback.

The app should not crash now.
