### ISSUE TITLE
Add ability to click on follower list in Profile

### ISSUE THREAD

**Issue by OddHouseGames** [mastodon/mastodon-ios#259]
Add ability to click on followers on our profile (to bring parity to web version) and for community engagement so that you can follow users back if you wish.![image](https://user-images.githubusercontent.com/62911518/128099182-ef11bda3-cdfb-41f3-8697-fb5876f03552.jpeg)

**Comment by MainasuK** [comment]
The feature is works in v1.2.0 (88) now.
