### ISSUE TITLE
Should be able to pull down on ‘search’ page to clear users you’ve added

### ISSUE THREAD

**Issue by OddHouseGames** [mastodon/mastodon-ios#263]
If you are on the search page and add users, then back on search page, it still shows users you have added.

You should be able to pull down to refresh to clear users from the recommended row to clear them from the list so you can focus on people you aren't following.

Even if you click over to the home tab etc then back to search, users you have followed still show up in the recommended list and even show 'follow' instead of following, but if you click on the profile, it shows you are following them.

I believe you have to close out the app to refresh this page.

**Comment by MainasuK** [comment]
Maybe you mean the "account recommend" right?

That list always updates when it displays. There will be appended to the list end if any new recommend. I can set it the list head, not the tail then see it works or not.

**Comment by OddHouseGames** [comment]
Ah I see, yes it is working correctly now.

I did notice that when you are on this main screen, you can't click on any of the follow buttons, you have to click the pic/name and the click the follow button on the next page. ![image](https://user-images.githubusercontent.com/62911518/128327952-c0bfe8ac-b669-4aeb-b3dc-afaf1f445756.jpeg)

If you can't use the follow button here, it should be removed or made active, because you have to click into the profile to use the follow button there.
