### ISSUE TITLE
Sounds doesn’t play in iOS

### ISSUE THREAD

**Issue by Kibranoz** [mastodon/mastodon-ios#266]
In video and music, we cannot hear the sound. 

Here are examples

https://mastodon.fedi.quebec/@manu/106700185962271467

https://mastodon.fedi.quebec/@manu/106690107369776694

It works on the web but not in the app.
```

**Comment by MainasuK** [comment]
Fixed in v1.0.3 (53). 
Thank you for your feedback.

**Comment by MainasuK** [comment]
And the video is default mute. Please tap the speaker icon to playback with audio.
