### ISSUE TITLE
[REQUEST]: remove character limit

### ISSUE THREAD

**Issue by Kibranoz** [mastodon/mastodon-ios#267]
Let's be honest. It really doesn't make sense. If I have a mastodon Post that's more than 500 characters I can just go into another app like Toot! And make my post. It's not based on any limits and not should there  be any limits to our speech.

**Comment by MainasuK** [comment]
related #222

**Comment by MainasuK** [comment]
The dynamic char limit works for servers which configure the char limits now. (https://github.com/mastodon/mastodon/pull/16485)
