### ISSUE TITLE
CW reveal instruction makes layout overflow on small screens

### ISSUE THREAD

**Issue by karthanistyr** [mastodon/mastodon-ios#277]
On small screens, the instruction to reveal a post behind a content warning does not wrap and may cause the layout of the CW screen to overflow out of the screen when the app is set to some languages (example: French)

app 1.0.5
iPhone SE v1

![5BE321DB-51D5-4068-9B9F-9B21CC00382D](https://user-images.githubusercontent.com/7722196/128849022-9f650f67-beab-4918-97b6-749b1d0d0051.jpeg)

**Comment by MainasuK** [comment]
The content warning layout fixed in v1.0.6 (58) now.
