### ISSUE TITLE
Change button titles to reflect Mastodon

### ISSUE THREAD

**Issue by BNolet** [mastodon/mastodon-ios#281]
The button to send out a toot is called “publish” when it should be Toot.

the button to boost has “reblog” on it when it should be written “boost”

just a few things that are reflecting tumblr more than they are Mastodon

**Comment by Gargron** [comment]
Publish and reblog reflect the original Mastodon. My decision not to use “toot” is final. I also believe reblog is more understandable than boost. Ironically, “boost” is tumblr-inspired terminology.
