### ISSUE TITLE
Nowhere in app to see instance/owner info

### ISSUE THREAD

**Issue by OddHouseGames** [mastodon/mastodon-ios#289]
Unless I missed it, there doesn't seem to be anywhere in the app where you can see the owner/instance info that you are part of.

Benefit: users would know who to contact for any instance specific issues.

**Comment by MainasuK** [comment]
You can check the `acct` (e.g. name@domain.com) label on the profile page. That label is next to the name label.

**Comment by OddHouseGames** [comment]
You can see it but can't interact with it.

I'm realizing now I supposed there shouldn't be a link to owner info because those are usually talking about supporting the instance/donations which is against Apple policy within the app.

I just thought it would be helpful because there is no incentive for new iOS Mastodon users to really think about the operating cost of the individual instance but I think our hands are tied here.

**Comment by MainasuK** [comment]
I see. The domain label is not enough for your need. 

Add an entry to server admin profile is possible. I'm not sure the user participate in community building or not. But for feedback is make sense. 

Currently, the user only could find an email or something in "Settings -> Terms of Service"

**Comment by zeitschlag** [comment]
Good news: In the new settings part you can see this information :arrow_right: #1126
