### ISSUE TITLE
Ability to follow/subscribe to hashtags

### ISSUE THREAD

**Issue by OddHouseGames** [mastodon/mastodon-ios#290]
It would be great to be able to follow/subscribe to hashtags like Pixelfed/Twitter

**Comment by tomfinitely** [comment]
This is another powerful feature of Mastodon that sets it apart from Over There 🐦, yet an entire class of users is omitted by forcing them to use a desktop browser to follow hashtags. In adding this feature I think it would be important to create a UI element in both the desktop and native app interfaces that indicates a followed hashtag post versus a standard post or reblog from our followings.

**Comment by j-f1** [comment]
This was recently added in https://github.com/mastodon/mastodon-ios/pull/691!
