### ISSUE TITLE
Replying to a self-reply creates two mentions

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon-ios#293]
Steps to reproduce:
1. With account A, make a top-level post.
2. With account A, reply to (1)
3. With account B, reply to (2)

Expected behavior: Account A is mentioned only once in the compose view

Actual behavior: Account A is mentioned twice in the compose view

**Comment by MainasuK** [comment]
Sorry for the late reply.

I just test two accounts under the same and different domains. But cannot reproduce this issue. The app already has filtered out the same accounts by `acct`. But the server may return different values so its may not works. Could you tell me which domain using for accounts A and B?

Thanks.

**Comment by trwnh** [comment]
Account A is on fedi.underscore.world (Pleroma)
Account B is on mastodon.social (Mastodon)
