### ISSUE TITLE
Unable to connect to my own server at home

### ISSUE THREAD

**Issue by punkrockgirl** [mastodon/mastodon-ios#298]
I'm running Mastodon v1.0.8 (60) on my iPad mini 4 (iPadOS 15.0), which I downloaded from the App Store.

I self host Mastodon (3.4.1) on my RaspberryPi4 running YunoHost (4.2.8.3)

Expected behaviour:
Type my server URL to add it to the iOS app.

Issue:
The app doesn't seem to find my instance.

BUT the app DOES see/find my instance from outside my home network (hotel, phone tethering…).

And even if I can't use my server on Mastodon for iOS when I'm connected to my home network, I DO receive push notifications regarding new followers or likes.

Now that my account/server has been added, when I try to access it from my home I get an OFFLINE message on top of the timeline (between Settings and Compose).

Extra info:
I can connect to my server using a web browser (desktop and iPad) or Fedilab and Tusky (Android) from within my home network. The issue only happens when trying to use Mastodon for iOS.

Due to hairpinning, I have Pi-Hole resolve all my DNS requests.

I am not a developer and so there is only so much information I can provide.
I believe my issue could be related to #184 and/or #260, which were closed over a month ago.

My server's "approval_required" is set to "false", if that helps.

Thanks

**Comment by MainasuK** [comment]
The app forces the domain connection with HTTPS protocol now. Maybe that prevents the app link to your server.
