### ISSUE TITLE
Issue when mentioning someone

### ISSUE THREAD

**Issue by MayMeow** [mastodon/mastodon-ios#300]
When you try to mention someone and you start writing name it's found list of users after clicking on it, this user is added to message but after sending it there are only those letters you have written manually, so mentioned user is not mentioned... look at video 

https://youtube.com/shorts/xlNsJGwJY2w?feature=share

My app version is v1.2.0 (74) from test flight

**Comment by MainasuK** [comment]
It looks like the text content is not updated after the key type. 

You can workaround it by typing a space temporary. 
And I'll fix it in the next release.

Thank you for your feedback.
