### ISSUE TITLE
GIF not showing in iOS app (but shows up in browser)

### ISSUE THREAD

**Issue by OddHouseGames** [mastodon/mastodon-ios#301]
https://mastodon.cloud/@boilingsteam/107150777997280091

The post above has a GIF which does not show up in the official iOS Mastodon app, but if I paste into a web browser I can see it.

Mastodon iOS app:
![image](https://user-images.githubusercontent.com/62911518/138556453-6eb6b59a-451b-4c82-910a-8a592a8ef706.jpeg)

Mastodon via DuckDuckGo iOS browser:

![image](https://user-images.githubusercontent.com/62911518/138556373-410b0c50-b74e-44cf-91af-bd05442fe234.jpeg)

**Comment by MainasuK** [comment]
<img src='https://user-images.githubusercontent.com/7940186/139810286-e3706e80-7282-4252-82ce-12e51ded8ca1.jpeg' width=300>

I use a new account on `fosstodon.org` and can not reproduce this issue. Is that always happens?  I have no idea about this.

**Comment by OddHouseGames** [comment]
Strange, and apologies, it must have been an issue on my end in the iOS Mastodon app, sorry and thanks for looking into it, you can close the issue.
