### ISSUE TITLE
show users who boosted or reblogged a post

### ISSUE THREAD

**Issue by foss-** [mastodon/mastodon-ios#308]
Currently it looks as if `x reblogs` was an interactive item. Tapping it does nothing.

Would expect to tap item and see who reblogged or boosted the specific post.

Not sure if this is a missing feature or if generally mastodon does not expose who shared a post as a privacy feature.

![boost](https://user-images.githubusercontent.com/5708172/143445051-190c7d4b-aca2-4588-b1f2-61780a3c692d.png)

**Comment by zeitschlag** [comment]
You can see the people who favorited/reblogged a post now.
