### ISSUE TITLE
Removed line breaks when editing profile

### ISSUE THREAD

**Issue by hansvurst-foss** [mastodon/mastodon-ios#311]
**Description**
When using the "Edit Info" Button on the profile description, all line breaks are removed in the editable view.

**Steps to reproduce**
Go to Users profile. Click on "Edit Info". See the description editable but with removed line breaks.

**Expected behavior**
Info should remain as set in the profile description.

OS: iOS 15.1
Device: iPhone 6S
App Version: v1.2.0 (88)

**Comment by newfangled0** [comment]
Can confirm that this bug is also happening for me.

OS: iOS 15.4.1
Device: iPhone SE (2016)
App Version: v1.3.0 (109)
