### ISSUE TITLE
RTL & LTR switch in server rules in the proccess of creating a new account

### ISSUE THREAD

**Issue by zer0-x** [mastodon/mastodon-ios#317]
Most of the server rules are written in English or other LTR laguage, so we need to switch the direction accourding to the language of the rules. (Both the text and the number icon)

I don't think there is a language value when setting the rules by the server admin, but it could be very usefull if there was.
<img width=200px src="https://user-images.githubusercontent.com/65136727/145127391-d4d70dd8-2dcd-4313-ba1a-71c6e43c3091.png">

**Comment by MainasuK** [comment]
This server rules scene was refactored. The issue should be resolved in v1.3.0 (109).

Thank you for your feedback.

**Comment by MainasuK** [comment]
Oh, yes.

Maybe I needs check the server language then force it LTR.
