### ISSUE TITLE
RTL, LTR and some UX in the registering page

### ISSUE THREAD

**Issue by zer0-x** [mastodon/mastodon-ios#318]
- For the usarname field I think the `@` should be **always on the left** since it require the use of english letters only. And I think we should find **another place** for the domine since it **might be very long** depending on the server.

- Both deisplay name and email fields are adaptable, when I start typing it switchs to LTR, **but the problem** is that when I delete what I wrote they don't return to RTL.

- For the password field, unlike the rest fields, it **does not** switch to LTR when you start typing.

- For the note under the password I think the second line should start from the same place as the first line.
<img width=200px src="https://user-images.githubusercontent.com/65136727/145131346-7c0b0422-ab1e-41f6-896b-33394a5787e8.png">

**Comment by MainasuK** [comment]
This scene gets RTL layout updates in v1.3.0 (109).

The system control may not meet the RLT usage here. Please file new issue and discuss what the control UX will be.
