### ISSUE TITLE
Icons are not switching to RTL in the popup menues

### ISSUE THREAD

**Issue by ZER0-X** [mastodon/mastodon-ios#319]
<img width=200px src="https://user-images.githubusercontent.com/65136727/145131596-8bfc3c86-2ce1-4a78-96b6-4a3e79291947.png">
<img width=200px src="https://user-images.githubusercontent.com/65136727/145131611-0368139f-c3b5-4a7a-b323-f6df1685645c.png">
<img width=200px src="https://user-images.githubusercontent.com/65136727/145131623-84cdd319-6736-41f1-88c8-303f7ab9f260.png">

**Comment by MainasuK** [comment]
Hi~

That's the iOS standard menu component. The icon is on the right side on LTR language and on the right side on RTL language. So that's should be a designed UI behavior.

**Comment by Gargron** [comment]
Indeed. On LTR layout, the icon is on the opposite side, so it's already doing the right thing.

**Comment by ZER0-X** [comment]
Oh, sorry, I thought it behaves like menus in desktop UI frameworks.
