### ISSUE TITLE
Add Basque language in Crowdin

### ISSUE THREAD

**Issue by aldatsa** [mastodon/mastodon-ios#320]
I would like to translate the app to Basque language. Please add the language in Crowdin. Thanks.

**Comment by MainasuK** [comment]
Hi~

The Basque language added now.

Thank your for your contribution.

**Comment by aldatsa** [comment]
Hi, I've just completed the Basque translation. It would be great if you could include it in your next release. Thanks!

**Comment by MainasuK** [comment]
I'll make it available in the next release.

Thank you for your contribution.
