### ISSUE TITLE
Use max_media_attachments API to follow instance-specified media upload limit.

### ISSUE THREAD

**Issue by HolgerHuo** [mastodon/mastodon-ios#321]
As the default upload limit for Mastodon is somewhat too low for SNS, some instances have bumped their media upload limit. Mastodon v3.4.2 has introduced max_media_attachments API to tell the client how many media files can be attached to one toot.
It will be great if mastodon-ios can follow this new feature to allow users upload more media files if allowed by the instance.

**Comment by MainasuK** [comment]
Sorry for the late reply. 

The app not fully use that API and only set the characters cap now.  Because the app can not display photos more than 4. I think this issue could be resolve after the media container refactor done.

Thank you for your feedback.

**Comment by HolgerHuo** [comment]
Thanks for your reply and developments!
Hope Mastodon and mastodon-ios are getting better and better in 2022!

**Comment by j-f1** [comment]
I think this issue is now fixed (looking at the code, the compose view seems to fetch and respect the max media count).

**Comment by HolgerHuo** [comment]
Thats great
