### ISSUE TITLE
Submission feedback in report dialog

### ISSUE THREAD

**Issue by Gargron** [mastodon/mastodon-ios#326]
Currently there is little feedback when you press one of the "submit" buttons at the end of the report dialog, and the buttons can be pressed multiple times resulting in multiple server-side submissions. Button should not be pressable while a report request is in flight, and we could have some kind of "Thank you for your report" screen with a green checkmark once it's done.

**Comment by MainasuK** [comment]
It's make sense. 

Before a UI design ready for it. I can set the button to checkmark or present an "alert".

**Comment by Gargron** [comment]
Closing in favour of #360
