### ISSUE TITLE
Add Kabyle language

### ISSUE THREAD

**Issue by BoFFire** [mastodon/mastodon-ios#329]
Hi, please add Kabyle `kab` language on Crowdin. Thanks.

**Comment by SelyanKab** [comment]
Yes, I am ready to translate the app in kabyle.

**Comment by MainasuK** [comment]
Hello,
The Kabyle language adds to the Crowdin and you can check it now. :)

**Comment by SelyanKab** [comment]
@MainasuK thank you :)

**Comment by BoFFire** [comment]
Thank you @MainasuK 🙏
