### ISSUE TITLE
Unable to connect with my TOR instance

### ISSUE THREAD

**Issue by k0gen** [mastodon/mastodon-ios#338]
I have a mastodon instance self hosted over Tor at http://a232ncr7jexk2chvubaq2v6qdizbocllqap7mnn7w7vrdutyvu32jeyd.onion/@k0gen that I want to use with your excellent Mastodon mobile app.

I use [Orbot.app](https://github.com/guardianproject/orbot-ios) that provides a "VPN" which tunnels all network traffic through Tor.

**The problem:**
I was unable to connect to my instance. The Mastodon app is unable to see/resolve my instance.

**Solution:**
Please allow *.onion domains resolution over HTTP protocol.

**Comment by Gargron** [comment]
Looks like this will be in the next release!

**Comment by k0gen** [comment]
That is awesome!
If you have a TestFlight for alpha/beta version go ahead and invite me, so we could do some tests before official release.
