### ISSUE TITLE
Conversion function not available on Japanese keyboard (shere & cw)

### ISSUE THREAD

**Issue by karin722** [mastodon/mastodon-ios#342]
# Summary
Conversion function not available on Japanese keyboard (shere & cw)

# reproduction procedure
## cw
1. Add Japanese keyboard in Settings.app in IOS
2. Launch Mastdon.app
3. Open the cw edit screen from the submit button
4. Enter characters with a Japanese keyboard. The conversion function is not available.

## shere
1. Open mastodon.app from the share sheet
2. Type characters with a Japanese keyboard on the posting screen that appears. The conversion function is not available.

# version
iPhone 13mini - ios 15.2
mastodon.app v1.2.0

**Comment by MainasuK** [comment]
The issue resolved in v1.3.0 (109).

Thank you for your feedback.
