### ISSUE TITLE
In-app browser loses interactivity

### ISSUE THREAD

**Issue by theDanielJLewis** [mastodon/mastodon-ios#344]
I haven’t tested this in previous versions, but at least in 1.3.0, the in-app browser loses interactivity after a page or two.

It happened for me simply from tapping the GitHub link inside the app. It took me to the GitHub page and I could tap “Issues,” but then I couldn’t tap on anything else after that.

**Comment by MainasuK** [comment]
The app uses the system in-app Safari browser to open links. Could you test another GitHub link, for example, this repo, to reproduce this issue? That's normal on my device now.

There is a template for the bug report now. 
https://github.com/mastodon/mastodon-ios/issues/new/choose

Please fulfill more context for this issue and I can try to help.

**Comment by theDanielJLewis** [comment]
I'm sorry, I haven't been able to replicate this. So maybe it was something going on with only my device. So I'll close this.
