### ISSUE TITLE
[BUG] The text view layout jumping when lines change

### ISSUE THREAD

**Issue by MainasuK** [mastodon/mastodon-ios#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The text view layout jumping when delete character cause lines number change.

### Expected Behavior

The text view keep the layout without jumping.

### Steps To Reproduce

1. Open Compose scene

2. Type some words more than 3 line 

3. Delete all character in the latest line

### Environment

```markdown
- Device: iPhone X
- OS: iOS 15.0.3
- Version: v1.3.0
- Build: 109
```

### Anything else?

https://user-images.githubusercontent.com/7940186/160725398-f7c085c2-44d1-4b20-a752-f4914bd21d81.MP4

**Comment by MainasuK** [comment]
Note:
There is a table view update with animation due to text view height changing.

**Comment by dasdom** [comment]
Why is this an update with animation? Shouldn't that be an update without animation?

**Comment by MainasuK** [comment]
> Why is this an update with animation? Shouldn't that be an update without animation?

It's some magic from `UITableView`. The compose scene is rewritten with `SwiftUI` in #533. It's should be fixed soon.
