### ISSUE TITLE
Support for iPhone 6 (iOS 12)

### ISSUE THREAD

**Issue by hdante** [mastodon/mastodon-ios#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to install the iOS Mastodon app on an iPhone 6 from the App Store, it says iOS 14 is required.

### Expected Behavior

Mastodon App should support iOS 12.5.5.

### Steps To Reproduce

1. Go to App Store and try to install the Mastodon app.
2. Error message stating that it requires iOS 14 or later.

### Environment

```markdown
- Device: iPhone 6
- OS: iOS 12.5.5
- Version: 1.3.1
- Build: unknown
```

**Comment by PaulWebster** [comment]
Same for iPad Air (1) which, at the time of writing, has maximum iOS of 12.5.6

Apple Xcode 14 seems to support building for iOS back to iOS 11 so perhaps Cocoapods could resolve this by simply setting the minimum platform version to 12.

**Comment by j-f1** [comment]
This is unlikely to happen since some portions of the UI are written using SwiftUI, and most of the data flow uses Combine and Swift concurrency. All of these require at least iOS 13.

**Comment by kimar** [comment]
As @j-f1 mentioned, we're depending on Apple Frameworks such as SwiftUI and technologies such as Swift Concurrency (async/await) which are both only available beginning with iOS 13, unfortunately this implies there is technically no way to support iOS 12.

Trying to support iOS 12 would have huge implications and prevent us from adopting modern Apple technologies which would ultimately hurt the App's UX.

I'm sorry I can't give you any more positive answer.

I'm going to close this issue now.
