### ISSUE TITLE
Delete & re-create

### ISSUE THREAD

**Issue by zerok** [mastodon/mastodon-ios#379]
Hi 🙂

The web interface currently offers a "delete & re-create" action for quickly basically fixing mistakes in posts. IMO it would be awesome if the iOS could also offer that functionality. Right now you'd have to copy a post's content, delete the post, create a new post and paste the previous content into that draft.

Thank you for your work on this app 😀

**Comment by Gargron** [comment]
We’ll just add editing, no point in adding delete and redraft now

**Comment by zerok** [comment]
Ah ok, thanks :)
