### ISSUE TITLE
Feature request: Support multiple user accounts

### ISSUE THREAD

**Issue by joncamfield** [mastodon/mastodon-ios#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current behavior is great for managing one single account (seriously, the app is *nice* !)

### Expected Behavior

It would be great to be able to manage multiple simultaneously-logged-in user accounts (across multiple servers) by switching the user in the app, with clear feedback on which user one is currently acting as, and the ability to log out / manage each fully (per current account options as-is) and switch (by clicking the user icon and selecting a different user or an option to add a new account). (the birdsite app actually has a good user experience here).

### Environment

```markdown
- Device:
- OS:
- Version:
- Build:
```

**Comment by Gargron** [comment]
Long press on your avatar in the bottom bar to add more accounts

**Comment by squio** [comment]
Excellent! I think this was mentioned during onboarding but I forgot
