### ISSUE TITLE
[BUG] App shows wrong language

### ISSUE THREAD

**Issue by janlindblom** [mastodon/mastodon-ios#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app is displaying Finnish labels instead of the expected Swedish or English ones. See attached image.
![AD614626-22A3-409F-8694-87F102B8DAB0](https://user-images.githubusercontent.com/154438/165302932-36e05808-417b-4e97-9a58-09900daf435c.png)

### Expected Behavior

App should have Swedish or English language labels, following the iOS settings and preference order.
![D78151C9-0AEE-45F6-B507-2AED9972D7D5](https://user-images.githubusercontent.com/154438/165303136-130ee23d-e6d3-4dc4-bf08-e05329e15334.png)

### Steps To Reproduce

Run the app in Finland with Finland as country/region and iOS language preferences set to Swedish, English, Finnish.

### Environment

```markdown
- Device: iPhone 11
- OS: iOS
- Version: 15.4
- Build: 19E241
```

**Comment by himynameisjonas** [comment]
I have the same problem and I don't even have Finnish/Soumi listed in languages on my phone: 
![IMG_FFC598218508-1](https://user-images.githubusercontent.com/39345/165503886-a3be59d0-b0e7-447f-bcbd-8d02035afe0f.jpeg)

**Comment by mikaelf** [comment]
I also noticed this and started a discussion: [Mastodon for iOS is in Finnish for Swedish people](https://github.com/mastodon/mastodon/discussions/18101).
I believe the issue is that the Finnish translation in the Mastodon for iOS app is in `Svenska (Finland)` (`Swedish (Finland)`). **Note** that there's a workaround to use English, that at least work on iPhones, see the linked discussion.

**Comment by MainasuK** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/7940186/165517981-1372cdff-0b40-4a63-8f0e-a5ba2244fdb2.png">

Yes, it's a bug. And the [Crowdin](https://crowdin.com/project/mastodon-for-ios) Swedish translation is still lacking. Please use the workaround and a build will release with unfinished Swedish i18n.

**Comment by janlindblom** [comment]
Alright, then I’m not alone! I’ll see if I can spend a little time on Crowdin for the Swedish translation. Thanks!

**Comment by janlindblom** [comment]
Ok, the Swedish translation is at 84% up from 19% now so should be a better experience!
Could probably do well with a few more pairs of eyes - I am experienced as a translator but I haven’t done Mastodon terminology before so might have missed something.

**Comment by janlindblom** [comment]
Swedish translations at 88%, new strings in #389 should be there too.

**Comment by mikaelf** [comment]
> Ok, the Swedish translation is at 84% up from 19% now so should be a better experience!
> Could probably do well with a few more pairs of eyes - I am experienced as a translator but I haven’t done Mastodon terminology before so might have missed something.

Great! I did another round Crowdin just now and got it to 99%!

**Comment by MainasuK** [comment]
Ship in v1.4.0.
