### ISSUE TITLE
[BUG] No UI for follow requests?

### ISSUE THREAD

**Issue by joncamfield** [mastodon/mastodon-ios#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an account set to requiring follow requests. I get notifications of being followed (which AFAICT is just the request), and can follow back, but there is not a way to "approve" the request until I go to a web UI.

### Expected Behavior

Follow requests should show up differently from follow notifications and offer approve/deny options

(Note that this is not an urgent thing, just a bug to note - I am loving the increased traffic and interaction happening in the fediverse!)

### Steps To Reproduce

Set a Mastodon account to requiring follow approval
Receive new follow requests
Try to approve the requests in-app only

(One note, I am running a personal server where this private instance lives, if that could be causing issues, it otherwise is working as expected)

### Environment

```markdown
- Device: iPhone XR
- OS: 15.4.1 
- Version: 1.3.1
- Build: 113
```

**Comment by mthld** [comment]
Strangely, it seems to be working now on v1.4.5 (144).

![image](https://user-images.githubusercontent.com/41020854/177212485-8af398a0-bedf-4d2d-a729-cac4bbe63b19.jpeg)
