### ISSUE TITLE
Central Kurdish

### ISSUE THREAD

**Issue by roj1512** [mastodon/mastodon-ios#393]
Hello there, I want to translate the app into Central Kurdish (`ckb`, "Sorani (Kurdish)" on Crowdin with the same flag as Kurmanji). Please add it to the Crowdin project.

**Comment by MainasuK** [comment]
Hello @roj1512 

Thank you for your contribution.
The "Sorani (Kurdish)" Crowdin language is available now. 

Please ping me when it ready although I'm integrate new language into app regularly.

**Comment by roj1512** [comment]
@MainasuK It is ready now :)

**Comment by MainasuK** [comment]
<img width="415" alt="i18n" src="https://user-images.githubusercontent.com/7940186/165900321-20f78493-c076-44a6-a5fe-d5d2b41eb9ea.png">

Hi @roj1512. Is the `ckb` lanugae code make sense for you?
Please correct me if that's needs changes.

Crowdin supports these three languages:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/7940186/165900629-a6d1706b-6107-4994-9e81-8f2e58585a73.png">

#### Current mapping:
Crowdin language name -> Crowdin language code -> iOS language code
- Kurmanji (Kurdish) -> kmr_TR -> ku
- Sorani (Kurdish) -> ckb_IR -> ckb

**Comment by roj1512** [comment]
@MainasuK yes, it is ckb.

**Comment by CYAXXX** [comment]
@roj1512 as i've been told mastodon for ios doesn't support mostly all languages, mastodon for ios, won't work for kurmanji/sorani kurdish at least in current period

**Comment by roj1512** [comment]
@CYAXXX Ne bira, iOS her du tê de ye. Wan weşanek nû weşandin û niha her du berdest in :)

![image](https://user-images.githubusercontent.com/49933115/166097115-b5193445-e90f-4ced-9a05-cee4f5d3bc1b.jpeg)

![image](https://user-images.githubusercontent.com/49933115/166097121-7aad3c77-4ca0-4767-b5ef-66ccd76f7b3c.jpeg)

**Comment by CYAXXX** [comment]
UI dibe soranî/kurmancî gava yekê ji wan hildibijêrî? Cara dawî berî 20-30 roj min test dikir ne dibû, cem min iOS tune android e, ber wê nikarim her roj bibînim

**Comment by roj1512** [comment]
Belê dibe :)

Dikarî bibînî:

![image](https://user-images.githubusercontent.com/49933115/166109070-c332f0a3-e17a-4922-9ea7-72bc6596a62e.png)
![image](https://user-images.githubusercontent.com/49933115/166109071-4ac587c0-84a7-4923-8313-7b5aa4d505de.png)
![image](https://user-images.githubusercontent.com/49933115/166109080-7099e985-5f6d-4ddb-8581-72c277abdde9.png)
![image](https://user-images.githubusercontent.com/49933115/166109083-1fb0da67-c914-4c14-b6ef-e671c7bd5c25.png)

**Comment by roj1512** [comment]
@CYAXXX dikarim binzanim çima Twitterê te nema? Bibore peywendiya pirsa min bi vir ve nîne...

**Comment by CYAXXX** [comment]
> @CYAXXX Ne bira, iOS her du tê de ye. Wan weşanek nû weşandin û niha her du berdest in :)
> 
> ![image](https://user-images.githubusercontent.com/49933115/166097115-b5193445-e90f-4ced-9a05-cee4f5d3bc1b.jpeg)
> 
> ![image](https://user-images.githubusercontent.com/49933115/166097121-7aad3c77-4ca0-4767-b5ef-66ccd76f7b3c.jpeg)

Spas mala te ava, kêfxweş bûm bi vê wêneyê, 


> @CYAXXX dikarim binzanim çima Twitterê te nema? Bibore peywendiya pirsa min bi vir ve nîne...

Period e diçim têm, dikarî di crowdin de bişînî

**Comment by roj1512** [comment]
@CYAXXX spas xweş. laşê te sax be û dilniya be qet mandîbûnên te bi zêde naçin :)
