### ISSUE TITLE
[BUG] Profile frozen after profile description update with name @alice & 999 values

### ISSUE THREAD

**Issue by RonanCodes** [mastodon/mastodon-ios#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating my profile multiple times with what seems to be the max allowed ( 520) characters in the description, my profile froze. 
I could use the app, but when I go to my profile it shows the @alice user, with 999 posts, following, & followers.
<img width="355" alt="image" src="https://user-images.githubusercontent.com/6930753/165749435-cb55870e-e3ef-48ed-af1f-8bf0bd6c63a5.png">

The iPad app is fine however.
Issue persists after reopening the app & restarting the iPhone.
I have a feeling an app reinstall is needed.

### Expected Behavior

Profile should save & not show the @alice account.

### Steps To Reproduce

Update profile with 520 characters with many new lines, multiple times.

### Environment

```markdown
- Device: iPhone 12 Mini
- OS: iOS
- Version: 15.4.1
- Mastodon Build: 113 (version: 1.3.1)
```

### Anything else?

Other related issues:
1. It's hard to know the max length allowed.
2. When you save, all your new lines disappear, so you need to make sure to write up your profile draft in a separate editor before copying and pasting in case you need to make an update to your profile.

Expectation:
1. When updating profile info, should show a counter of max length allowed.
2. Should keep new line characters intact when editing your profile.

**Comment by MainasuK** [comment]
That's is some layout issue only happens on some devices.
And it should be fixed in v1.4.3.
