### ISSUE TITLE
[BUG] Tapping navigation tab button doesn't scroll to top

### ISSUE THREAD

**Issue by aurynn** [mastodon/mastodon-ios#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I am viewing the Home timeline, tapping on the Home navigation button at the bottom of the screen does not scroll to the top of the Home feed.

The same bug exists for the Notifications tab.

### Expected Behavior

When tapping on the Home, Notifications, or other tab, I expect the app to scroll me to the top of the navigation view, as if I'd tapped the top of the screen/navbar.

This behaviour exists in other social media apps that I use (Twitter, Tweetbot, Metatext, tooot).

### Steps To Reproduce

1. Open Home timeline
2. Scroll down
3. Tap the Home tab button

### Environment

```markdown
- Device: iPhone XS
- OS: 15.4.1
- Version: v1.3.3
- Build: 116
```

**Comment by MainasuK** [comment]
Hello @aurynn. 

The app supports tap-to-top gesture. Could you close the app and try again. 🤔

**Comment by aurynn** [comment]
Hi @MainasuK;

Ah, I must've just had an older version, can confirm that on 1.4.0 it's working as expected. 🙂
