### ISSUE TITLE
First-run: "log in" button goes to "sign up"/discovery flow

### ISSUE THREAD

**Issue by jpluscplusm** [mastodon/mastodon-ios#402]
Version 1.3.1. iPhone 11. 

On first-run, with no accounts ever having been present on the device, the very first page of the app offers a choice between "Get Started" and "Log In". 

Both of these buttons enter the "discovery -> signup" flow. 

The "log in" button simply doesn't show a page that would allow one to enter custom instance details. 

I assume this is a bug, and not intentional. I could record a video of it happening, but I'm 100% sure it's not user error. I'm not accidentally selecting the "Get Started" button. There are no other choices to make.

Both buttons enter the same flow, hence I suspect the app is effectively completely broken for new devices (distinct from new _**users**_).

**Comment by MainasuK** [comment]
That's maybe some confusions from the second page. That's indeed a same page what ever your choice. But the differnt behavior will triggered when tap the "Next" button.

**Comment by iaalm** [comment]
> That's maybe some confusions from the second page. That's indeed a same page what ever your choice. But the differnt behavior will triggered when tap the "Next" button.
> 
> Also, you can input the custom server domain in search textfield for login.

I have to say this is very confusing behavior. I can't figure out how to login until I see this thread.
May I suggest to add something like "Or enter URL for custom server" to that text box?

**Comment by tdelmas** [comment]
I confirm that some users are confused : they choose "log in", and then they are told to choose a server, **any server**, so if they didn't choose the one they used to create the account, it will not work.

**Comment by AxelBoldt** [comment]
I'm here because I was just going to file a bug report about this same issue. It is a bug, not a "question". If I click on "Log in", I expect to be able to enter my account name and password; I don't care about the variety of servers that exist. I don't think I'm alone in this.

**Comment by j-f1** [comment]
I don’t think there’s a way to allow folks to enter their username and password directly after tapping the “Log in” button since we don’t know what server their account would be on. Maybe this can be fixed by changing the copy when you tap the “Log in” button?

> **Select your server to sign into Mastodon**
> Make sure you select the same server you signed up with!

**Comment by tdelmas** [comment]
>  we don’t know what server their account would be on.

True, but the login could be a user-name field, and if the user writes its full username, then ask directly the password (as the full username contains the server name), else ask the server then the password

**Comment by j-f1** [comment]
You have to log in to the server with your email address (at least on the 3–4 servers I checked), so the app wouldn’t be able to log in with just your username+password. That said, if you do paste your username into the input field it will pick up the corresponding server name and take you to the login page

**Comment by iaalm** [comment]
Could I suggest we just give user three input boxes to input username, password, and server url if choosing "Login". When they typing server url, there can be a drop-down box or something searching for matching server? This is just more straightforward.
From my personal experience, I known how maston works, but first time I just don't known what to do when I see "login" and "sign up" give me same page. At that time I think that must be a code bug until I see this thread.

**Comment by j-f1** [comment]
I think this may be resolved by the changes in #551.
