### ISSUE TITLE
Allow swipe right anywhere on a toot thread to navigate back

### ISSUE THREAD

**Issue by cpeterso** [mastodon/mastodon-ios#407]
To navigate back from a toot reply thread to your main feed, you must swipe right from the left edge of the screen, whereas Twitter and Instagram will navigate back of the user swipes right anywhere on the screen’s content area.

This  UX change would make jumping between your main feed and toot reply threads faster and easier.

The Mastodon app already supports switching back and forth on the Search screen’s Posts/Hashtags/News sections by swiping left or right anywhere on the content area.

**Comment by MainasuK** [comment]
You can try new pan gesture in v1.4.2 now.
