### ISSUE TITLE
Expose ALT-Text on images in the timeline

### ISSUE THREAD

**Issue by ericyahhh** [mastodon/mastodon-ios#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Create a new post
- Add an image and add an ALT-text to it

- Inside the timeline there’s no UI that indicates if an image has an ALT-text attached to it
- The ALT-Text also isn’t exposed visually in any way

### Expected Behavior

- Would be great to have an indicator that shows if an image has an ALT-text attached
- And if it has, there should be a way of displaying that text to any user 

### Environment

```markdown
- Device: iPhone 12 Mini
- OS: 15.4.1
- Version: 1.4.0
- Build: 121
```

**Comment by FediVideos** [comment]
Had a lot of new people asking about this recently, wondering how they can see the alt text on the official app. They are using alt text to make their posts accessible, but there's no way to check that the alt text is there or correct.

Also, a lot of non-disabled people like to see alt text as it often includes extra details and context about an image.

**Comment by jernst** [comment]
Just came across an image of a statistic, where the source of the data was only given in the ALT text. This meant I could not find out about the source of the data without moving to my laptop.
