### ISSUE TITLE
Audio attachments are not shown

### ISSUE THREAD

**Issue by alexreid** [mastodon/mastodon-ios#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When viewing a post with an audio attachment, no audio player is shown. 

Additionally, there is no indication that the post has an audio attachment.

### Expected Behavior

When viewing a post with an audio attachment, an audio player is shown to allow the user to listen to the audio. 

Alternatively, there should at least be a message warning the user that they cannot listen to the audio attachment in the app, possibly with a link to open the post on the web so the web player can be used.

### Steps To Reproduce

1. In the iOS app, load a post in the home timeline (or post details screen) that has an audio attachment

### Environment

```markdown
- Device: iPhone 11 Pro
- OS: 15.4.1
- Version: 1.4.0
- Build: 121
```

### Anything else?

[Example post where I see the issue](https://mastodon.social/@rmrenner/108230206074707414)

My server is tech.lgbt, which is running Mastodon 3.5.1.

**Comment by quardbreak** [comment]
Some people encountered this issue:
https://mastodon.social/@acb/109303147208739786
https://mastodon.social/@gloom303/109303533814308501
This might be better to be fixed ASAP.

**Comment by hsn10** [comment]
Second problem is that if you use show in safari on post then it will show audio but it won’t play smoothly, audio is breaking. Probably visualize function is using too much CPU.
