### ISSUE TITLE
Finish in Swedish iOS when Sign up

### ISSUE THREAD

**Issue by fracii** [mastodon/mastodon-ios#415]
Where to change language, English is better or Swedish. Finnish I Can not understand :)

**Comment by MainasuK** [comment]
Could you check the app version? The v1.4.0 should fixes it by add the missing Swedish language.

And you can workaround by set the app language in Settings:
1. Open iOS system "Settings" app in Home screen
2. Search "Mastodon" and tap it
3. Select your primary language
