### ISSUE TITLE
[BUG] Own profile's following count doesn't update

### ISSUE THREAD

**Issue by vollkorntomate** [mastodon/mastodon-ios#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the "My Profile" tab (where you see your own profile), the number of accounts I follow (following count) doesn't update. In my case, the displayed value is 3, but it should be 7.

Restarting the app or refreshing the view (by pulling down) both don't help.
The only thing that did help was to create a new post, reloading the timeline and then going back to the profile tab.

The number of posts as well as the follower count also seem to be affected. After I deleted the aforementioned post, the number of posts still shows 1 instead of 0.

### Expected Behavior

The number updates each time the tab is refreshed (by pull-to-refresh) or reloaded after restarting the app.

### Steps To Reproduce

1. Go to your profile tab
2. Look at the number of accounts you follow ("Following")
3. Remember that number
4. Search for an arbitrary user you don't follow yet and start following
5. Go back to the profile tab and pull to refresh
6. Observation: the following count didn't change

### Environment

```markdown
- Device: iPhone X
- OS: iOS 15.4.1
- Version: 1.4.0
- Build: 121
```

**Comment by jtsom** [comment]
Also seeing this. My profile numbers never update. Any movement on this?

**Comment by jverkoey** [comment]
Also running into this. Going to take a stab at seeing if I can find the bug in the source.

**Comment by ekazakos** [comment]
Relevant to this, I found out that if you are in your profile and you press **Edit Info** the followers/following counters do update.
