### ISSUE TITLE
[Feature] Swipe anywhere on the screen to go back

### ISSUE THREAD

**Issue by vollkorntomate** [mastodon/mastodon-ios#419]
This is an idea that I'd like to discuss. It is inspired by the way Twitter and many other apps handle the swipe-to-go-back gesture.

By default in iOS, when there are multiple `UIViewControllers` in a `UINavigationController` and a "Back" button is there, it is possible to go back one view controller by swiping from the edge of the screen. This is also the current behavior in Mastodon.

Twitter and many other apps, however, also allow going back by swiping anywhere on the screen, so not just from the edge. This is especially convenient on larger phones or for easier navigation in general. In order to improve user experience, this could be implemented into Mastodon as well.

I already did some basic research on this and implementing it seems to be quite easy.
[Here](https://stackoverflow.com/a/60598558/10295689) is a very good answer from StackOverflow providing a small code snippet that seems to do exactly the described behavior. Even better, it only needs to be implemented once and will become available to every view controller in the app without the need to change and maintain hundreds of files.
I quickly tried it out by integrating the code snippet into [`AdaptiveStatusBarStyleNavigationController`](https://github.com/mastodon/mastodon-ios/blob/main/Mastodon/Scene/Share/NavigationController/AdaptiveStatusBarStyleNavigationController.swift), which is the only sub-class of `UINavigationController` in the Mastodon project.

So, it seems that implementing this feature is a matter of minutes, with tests still to be conducted thoroughly. In my opinion, Mastodon should have this small feature as it greatly improves UX and because users joining from other platforms are already used to this kind of gesture.

**Comment by MainasuK** [comment]
Thank you for you suggestion. This feature available in v1.4.2 now.
