### ISSUE TITLE
Support user completion in share sheet

### ISSUE THREAD

**Issue by apfelnutzer** [mastodon/mastodon-ios#420]
When you post something using the share sheet the editor does not support user completion when you type the @-sign (as it does within the app. Thus it's practically impossible (or at least hard) to mention someone from another instance.

**Comment by zeitschlag** [comment]
It does now

![IMG_8BD187182836-1](https://user-images.githubusercontent.com/2580019/202981088-096056ed-3dc7-4ff0-a8e9-d326209524e2.jpeg)
