### ISSUE TITLE
Naming for community tab is inconsistent

### ISSUE THREAD

**Issue by apfelnutzer** [mastodon/mastodon-ios#422]
On the web that timeline ist called "Lokal" (in German, meaning "local" - in the app it's called "Community". That sort of confuses new users. Moreover I wouldn't expect that timeline in the search section. By the way: where to find the "Föderation" timeline (german for federation)?

**Comment by MainasuK** [comment]
Hi @apfelnutzer. 

The tab name is intent to be the "Community" on mobile now. Sorry for the confusion and there is not supports the federation timeline yet.

**Comment by apfelnutzer** [comment]
I'd prefer to have access to all three timelines and maybe have a common timeline view with the ability to switch focus between the three of them (as it's solved in Metatext for example). Moreover I suggest to stick with already established naming conventions.

**Comment by eruizdechavez** [comment]
Having the three timelines is one of the reasons why I keep coming back to Mastodon. I can live with a renamed tab or a semi hard to find tab, but not with missing/removed features 😓. 

I LOVE the look and feel of the official app in iOS 🥰.
