### ISSUE TITLE
[BUG] Mentions do not seem to be loading for me.

### ISSUE THREAD

**Issue by BigZaphod** [mastodon/mastodon-ios#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I first started using the native app on iOS, it seemed to work fine, but maybe 2 updates ago I noticed that my "Mentions" timeline was no longer updating. I figured it'd be fixed eventually and just used the "Everything" notification timeline instead, but there have been a few updates since then and I'm starting to think maybe this is not a problem everyone is having. :)

At first I left it in a state where the Mentions showed old posts that were out of date. Just today I decided I'd try signing out and back in again to really nuke the client's cache/config, but that didn't work either. Now the Mentions tab is just empty. Pulling to refresh shows the spinner, but it never seems to stop (until I switch away to another view and then back). Not sure if there's a good way to see any error logs for this.

### Steps To Reproduce

I have no idea what caused it or how to reproduce it.

### Environment

```markdown
- Device: iPad Pro 11" (2018, I think) and iPhone X.
- OS: both iPadOS and iOS on both the last released stable OS and on iOS 16 betas.
- Version:1.4.3
- Build: 138
```

### Anything else?

I'm @bigzaphod@mastodon.social.

**Comment by kevquirk** [comment]
I'm having the same issue. Thought it might have been my ad blocker (1Blocker) accidentally blocking it. Disabled the ad blocker and the issue still occurs.
