### ISSUE TITLE
[BUG] Profile's About section shows nothing

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon-ios#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you click on the About section of a profile, it says "no results".

### Expected Behavior

It should show the metadata that the user filled in (such as website etc). Previous versions of the app did do this correctly.

### Steps To Reproduce

1. Go to a profile page
2. Click About
3. Observe it says No Results

### Environment

```markdown
- Device: iPhone 11
- OS: iOS 15.5
- Version: v1.4.3
- Build: 138
```

**Comment by MainasuK** [comment]
PR #454 should fix this. But the build is still not released to App Store. 💭

**Comment by FediVideos** [comment]
Okay, thanks for update!

**Comment by MainasuK** [comment]
The v1.4.4 is ready on App Store now. 
Please update and verify the fix. :)

**Comment by FediVideos** [comment]
Thank you, updated and verified as working now!

Brilliant :clap:
