### ISSUE TITLE
[BUG] Images (from Pleroma) not being displayed in toots

### ISSUE THREAD

**Issue by AndrzejL-eu** [mastodon/mastodon-ios#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello.

I've installed the Mastodon app from Apple Store today (20th July 2022) and I've logged into my private / self-hosted pleroma installation. The images in toots are not displayed. At all.

### Expected Behavior

Images being displayed in toots that contain them. Example:

In the "Toot!" app:

![IMG_3986](https://user-images.githubusercontent.com/12524148/180095561-d63d244d-ef76-4b4a-b015-d0e6492932e2.PNG)

![IMG_3983](https://user-images.githubusercontent.com/12524148/180095582-3a09b825-0347-4dfd-aa3f-f95e4b3ca956.JPEG)

In the "Mastodon" app:

![IMG_3987](https://user-images.githubusercontent.com/12524148/180095608-d0e50eee-6801-4630-b487-96d38f66baf0.JPEG)

![IMG_3985](https://user-images.githubusercontent.com/12524148/180095616-2f8a85ec-500e-457d-9142-2ff296c95cdf.JPEG)

### Steps To Reproduce

Install and start using Mastodon app. No special steps were needed. Images were not loading as soon as I've installed the app and logged into the instance today.

### Environment

```markdown
iPhone 13 Pro Max

iOS 15.6

Mastodon 1.4.5 Build 144

Mastodon instance:
custom git-clone Pleroma
Backend version [2.4.3]
Frontend version [b13d8f7e]
self-hosted instance / Debian 11
https://docs-develop.pleroma.social/backend/installation/debian_based_en/
```

### Anything else?
Thank you for your work and for any help provided.

Kindest regards.

AndrzejL

![IMG_3989](https://user-images.githubusercontent.com/12524148/180097539-fc3b643c-2fb0-4520-8710-c636f0014c8b.JPEG)

![IMG_F5F5D0344229-1](https://user-images.githubusercontent.com/12524148/180098935-5e38d990-3f93-4b77-9320-34609386821c.jpeg)

![IMG_3988](https://user-images.githubusercontent.com/12524148/180097550-66c0676a-d166-4b60-b1a9-be2426810b8a.JPEG)

![image](https://user-images.githubusercontent.com/12524148/180097559-2a2f925a-be5e-4664-8f8a-0d74b93d4dee.png)

**Comment by MainasuK** [comment]
Confirmed. 

Sorry the late reply. I'll make a patch later.

Thank you for your feedback.

**Comment by sxpert** [comment]
just installed the pleroma server and the mastodon app today, and problem appears to still be there

**Comment by andydavidson** [comment]
Hi - I have the same problem. Pleroma as the instance host, latest IOS client, and everything works except images. I can post with media from the iOS client and the image shows up in the web interface and shows up in Metatext, but doesn’t appear in the Mastodon iOS app. You can look at @andyd@andyd.uk for an example. Thanks.

**Comment by sxpert** [comment]
I gave up and installed Metatext

**Comment by hutt** [comment]
Same bug here. iOS 16.1, app version 1.4.5 & I'm using a pleroma server as well. That's so frustrating.

**Comment by j-f1** [comment]
My hypothesis is that much like in the case of Friendica (#310), Pleroma isn’t providing size information for media attachments. The Mastodon iOS app currently filters out any media attachments that don’t provide both a `width` and a `height` property.
