### ISSUE TITLE
[Feature] Support bookmarking posts

### ISSUE THREAD

**Issue by stragu** [mastodon/mastodon-ios#478]
Currently, there is no option to bookmark a post. It would be great to be able to use that feature from the app.
In my opinion, the area below a post's contents offers plenty of space for an extra button, but it could alternatively be in the three-dot menu just like in the multi-column web interface.

**Comment by stragu** [comment]
Right, just saw that was the latest thing merged into the develop branch: https://github.com/mastodon/mastodon-ios/commit/28267fe6d8e4712942e54b2d99f59d62e0d7287c

I'll close this then! :smile:

**Comment by MainasuK** [comment]
Yes. That feature already merged. 

And I do not intend to delay to release it. Just have some refactor and bugfix stuffs to do. I'm trying to blance my workflow among several projects and hope that feature could release before a long wait.
