### ISSUE TITLE
[feature] bookmark

### ISSUE THREAD

**Issue by Alicebond** [mastodon/mastodon-ios#479]
Hi, thank you for making this nice app, it's really great to use. I just find the app doesn't have bookmark feature, could you add it?

**Comment by andypiper** [comment]
Since v4 is starting to hit release candidate status, I'd also like to see bookmarking in the iOS app. FWIW a few other iOS apps (Toot, Mastoot, Tusker) do have the feature already.

**Comment by andypiper** [comment]
Looks like this is now implemented in v1.4.7 (which is in the App Store, but not listed as a release here on GitHub?)

**Comment by Alicebond** [comment]
As the new update added this feature, I will close this issue.
