### ISSUE TITLE
[FEATURE] setting to hide boosts

### ISSUE THREAD

**Issue by nrchtct** [mastodon/mastodon-ios#481]
In the web interface, it is usefully possible to hide all reblogs/boosts. It would be really wonderful to have such an option in the settings of the iOS app.

**Comment by zeitschlag** [comment]
Hey @nrchtct,

thank you for your suggestion and I totally agree with you 🙂 

As a matter of fact, there's already an issue for that: #365 
I'll take care of that issue shortly, but for now I gonna close yours as a duplicate :)

**Comment by nrchtct** [comment]
Thank you 😊

**Comment by nrchtct** [comment]
Actually, #365 is about setting the display of reblogs per person one is following. But my feature request above was about hiding all reblogs in the home timeline, which is something that the web GUI actually has a filter option for (see screenshot). This is what I meant. Is this something in the works for the app, @zeitschlag? Thank you

![87DA5105-CBD2-489D-B88E-279D53F2060D](https://user-images.githubusercontent.com/578924/204076859-e813a2b0-6517-4a44-b81b-40ba8d7cf378.jpeg)
