### ISSUE TITLE
[BUG] Unable to build with Xcode 14 due to cocoapods-keys dependency

### ISSUE THREAD

**Issue by NanoSector** [mastodon/mastodon-ios#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A problem in what appears to be Xcode 14 prevents the project from being built on Apple Silicon Macs.

This problem is tracked upstream: https://github.com/orta/cocoapods-keys/issues/232

### Expected Behavior

The project can be built on Apple Silicon.

### Steps To Reproduce

1. Set up the environment as described in SETUP.md
2. Run `bundle exec pod clean`
3. Observe error

### Environment

```markdown
- Device: 14" MacBook Pro w/ M1 Pro
- OS: macOS 13.0.0
- Version: N/A
- Build: N/A
```

### Anything else?

cocoapods-keys has not been updated since 2020, with its upstream dependency osx_keychain last being updated in 2018 and throwing various deprecation warnings. Perhaps it is time to look into alternatives? The project itself links to https://github.com/rogerluan/arkana as a possible alternative.

**Comment by tejuamirthi** [comment]
Have you tried using the above with terminal using rosetta, just in case. The xcode might still be used without rosetta.

**Comment by NanoSector** [comment]
@tejuamirthi In the linked issue, people have tried running with Rosetta.

However as of #477 this should be fixed, I will double check and close this issue if so.

**Comment by sawalon** [comment]
https://github.com/orta/cocoapods-keys/issues/217#issuecomment-1304420876
fixed my issue.
