### ISSUE TITLE
[Feature] iOS Builtin Translation for Trööts

### ISSUE THREAD

**Issue by je1980** [mastodon/mastodon-ios#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Possibility to translate comments with iOS-built in translation e.g. „switch to German“ 

### Environment

```markdown
- Device:
- OS:
- Version:
- Build:
```

**Comment by zeitschlag** [comment]
Hello @je1980,

thank you for that suggestion. Unfortunately, Apple doesn't provide an API to the Translate-App, so we can't solve this from the programming side of things. But what you could do instead, is this:

Select the text you want to have translated as if you want to copy it and then press the little arrows to the right until you see "Translate", like this:

https://user-images.githubusercontent.com/2580019/199965512-1148c192-13d1-44ae-a25c-20753161278d.MP4

("Übersetzen" is just the German translation for "Translate")

Does this solve the issue at hand? 🙂

**Comment by david-coyle-sjc** [comment]
You can at least implement the Vision APIs for text recognition in images, that will offer translation when available.

**Comment by j-f1** [comment]
I started looking into this but was turned away by the complexity of the code. There’s a translation endpoint `POST /api/v1/statuses/:id/translate` that will handle the translation if your server supports it, and `/api/v2/instance` includes a `configuration.translation.enabled` boolean value that tells you if support is available. I think it would make sense to add a new set of translation-related properties to the Status `NSManagedObject`, set them when the user requests a translation, and clear them when they hide it. (in particular, that would be the translated post content, the detected original language, and the translation provider).

Then a new UI would need to be wired up in `StatusView` to surface these controls, and handling for that button would need to be passed up the delegate chain.

**Comment by zeitschlag** [comment]
Translation is implemented in #741 (if the server supports it)
