### ISSUE TITLE
[FEATURE] Improve Login Flow

### ISSUE THREAD

**Issue by zeitschlag** [mastodon/mastodon-ios#540]
- ~~Not accepting new members~~ -> Postpones
- [x] Remove emojis
- [x] Update validation-failed-appearance
- [x] Update texts (on Crowdin)
    - [x] _Create Account_ instead of _Sign up_
    - [x] Long explanation text

![Screenshot 2022-11-09 at 12 41 55](https://user-images.githubusercontent.com/2580019/200821809-f472397c-b94e-4276-adb3-bc3694dd39ee.png)

- [x] Login-Flow

![Screenshot 2022-11-09 at 12 42 01](https://user-images.githubusercontent.com/2580019/200821829-ed485f6b-aa22-4338-9458-87dd0ee89eac.png)

**Comment by jverkoey** [comment]
One idea for improving onboarding: next to the list of "All, general, regional, etc...", add a single tab for "URL" to make it clearer that there's an option for specifying an exact server URL. I personally bounced off of the Mastodon app three or four times before I realized I could type in any given URL and load the server, and I think if it had a clearer separation between the explicit flow (provide a URL) and the browse flow (all the other tabs), this would help the user navigate to the right flow for them.

It might make sense to have a vertical divider between the "URL" tab and the others as well.

**Comment by zeitschlag** [comment]
Hey, @jverkoey Thank you for that suggestion, I like it and I just passed it on to the UX/UI-people working on an improved onboarding :)

(And I might have renamed this issue to make it clearer, that this is about an improved _login_, only 🙈 )
