### ISSUE TITLE
Suggestion: three-dot menu next to user name should allow for Follow/Unfollow

### ISSUE THREAD

**Issue by AxelBoldt** [mastodon/mastodon-ios#558]
When I see an interesting toot, I often want to follow the author. Currently, this requires tapping on the author's profile picture and then tapping on "Follow".  

I think it would be more convenient and more intuitive if I could tap on the three-dot menu to the right of their name (which currently gives the options Mute/Block/Report/Share) and choose (Un)Follow from here. The same three-dot menu also exists at the top of the author's user page, and there the option (Un)Follow also would make sense.

I'm using Mastotodon for iOS v1.4.5 (144) on iPadOS 15.7.

**Comment by thadguidry** [comment]
# Clarify info:
"tapping" on ellipses menu in top right of post will not work to reproduce.  The ellipses menu must be touched and held for more than 1 second.

**Comment by zeitschlag** [comment]
The option to follow or unfollow the author of a status is there:

<img width="394" alt="Screenshot 2023-11-04 at 10 20 37" src="https://github.com/mastodon/mastodon-ios/assets/2580019/b3d4cb17-25a6-4365-86e0-44015a04a71f">
