### ISSUE TITLE
[Suggestion] Multiple instances support

### ISSUE THREAD

**Issue by sky-leonellima** [mastodon/mastodon-ios#562]
### Is there an existing issue for this?
Nope

- [X] I have searched the existing issues

### Current Behavior

Currently I see myself wanting to keep 2 instances, one at mstdn.social and another one at gamedev.social
Every time I want to switch instances I have to logout and login.

### Expected Behavior

Support multiple instances and switch between them seamlessly.
There could be a feature like instagram's multiple accounts.

### Environment

```markdown
- Device:iPhone 11
- OS:iOS 16
```

**Comment by zeitschlag** [comment]
Hello @sky-leonellima,

thank you for the suggestion. You know, that you can have multiple accounts in the app, right? Double-tap-and-hold-your-finger on the Profile-image in the TabBar at the bottom of the screen:

https://user-images.githubusercontent.com/2580019/201333294-5e5160cd-bcb0-4695-bd47-49a6cd7fb8f6.mp4

Does this solve your issue?

**Comment by j-f1** [comment]
Maybe we could add a hint next to the sign out button with something like "Tip! Long-press your avatar in the tab bar to sign into multiple accounts"?

**Comment by sky-leonellima** [comment]
Whoa, that's fast reply. I totally didn't know about that! Thank you ;)
