### ISSUE TITLE
[BUG] WelcomeViewController breaks in landscape

### ISSUE THREAD

**Issue by jverkoey** [mastodon/mastodon-ios#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Simulator Screen Shot - iPhone 14 Pro - 2022-11-12 at 11 36 12](https://user-images.githubusercontent.com/45670/201491580-dee56341-0656-4f70-8880-0bb65d70ac91.png)

See the attached image. Note that buttons become illegible and the background image is unnaturally stretched.

### Expected Behavior

At a minimum, the buttons should still be tappable.

Ideally, the background imagery would also adjust to handle the new orientation.

In the worst case, landscape mode should be disabled until the behavior above can be addressed.

### Steps To Reproduce

1. Launch the app in a first run context.
2. Rotate the device to landscape.
3. Observe.

### Environment

```markdown
- Device: iPhone 14 Pro
- OS: iOS 16
- Version: develop (f18abb336b80ca7480c0fce77f237bbc7ac48fcb)
- Build:
```

**Comment by jverkoey** [comment]
Note that I can't reproduce this in the production build. This might be a regression on `develop`?

**Comment by zeitschlag** [comment]
It's more of a `Debug`/`Release`-thing. Although all orientations are supported in `Info.plist`, the [`AppDelegate`][appdelegate] is to blame here:

```swift
extension AppDelegate {
    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        #if DEBUG
        return .all
        #else
        return UIDevice.current.userInterfaceIdiom == .phone ? .portrait : .all
        #endif
    }
}

```

[appdelegate]: https://github.com/mastodon/mastodon-ios/blob/develop/Mastodon/Supporting%20Files/AppDelegate.swift

**Comment by jverkoey** [comment]
Ah! Good to know, thank you :) is it worthwhile keeping a bug open to track landscape support in general?
