### ISSUE TITLE
[BUG] No indication that a post has been edited

### ISSUE THREAD

**Issue by j-f1** [mastodon/mastodon-ios#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Posts which have been edited, such as https://fediverse.zachleat.com/@zachleat/109348367567841205, do not show any indication of having been edited.

### Expected Behavior

At a minimum, an indicator should be shown somewhere that tells users the post has been edited.

Additionally, it would great to have a sheet that can be opened when tapping the indicator (at least when the post is expanded) that shows the full edit history of the post.

### Steps To Reproduce

Open https://fediverse.zachleat.com/@zachleat/109348367567841205 in the Mastodon app

### Environment

```markdown
- Device: iPhone 13 Pro
- OS: iOS 16.2
- Version: `develop`
```

### Anything else?

Related: #591

**Comment by zeitschlag** [comment]
This issue has been fixed in the meantime, looks like this now:

<img width="370" alt="Screenshot 2023-12-20 at 14 44 24" src="https://github.com/mastodon/mastodon-ios/assets/2580019/652377f5-8190-44e8-89a9-9a8bb4684707">
