### ISSUE TITLE
[BUG] two issues related to photo text

### ISSUE THREAD

**Issue by JJKraw** [mastodon/mastodon-ios#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1) When I tap on the space to enter text for a photo, there is no clear indication (like a "|" character replacing "describe photo for...") that it is ready for me to enter text.  Only upon typing is that clear.

2) If I enter a photo first and then add text to it, there is no way I can enter text back up on the "Type or paste what's on your mind" area. Tapping on that area doesn't make it work. Any entered text is appended to the photo description. Doing the reverse ("type or paste" text first) works fine.

### Expected Behavior

1) Some indication that any text typed after tapping on the photo description area will actually end up there.

2) Should be able to enter general text after photo insertion.

### Steps To Reproduce

1. Compose a new toot.
2. Insert photo.
3. Tap the area to add photo text.
4. Try to tap the area above to add general text.
5. At this point, any text added will still go to the photo description.

### Environment

```markdown
- Device: iPhone SE (2 gen)
- OS: iOS 
- Version: v1.4.7
- Build: 196
```

### Anything else?

<img width="331" alt="Screen Shot 2022-11-18 at 08 05 54" src="https://user-images.githubusercontent.com/67399409/202713789-d5119692-377b-4ee7-8369-77ce5357edf2.png">

**Comment by jeffpc** [comment]
I have an observation about the second issue (not being able to type the toot text after attaching an image).  I noticed that it *sometimes* is possible to type text after attaching a photo, but getting the "focus" to move is a bit of an art.

If I write 7+ lines of text before I attach an image, I can then semi-reliably tap around the text 10+ times and eventually get a word highlighted. Once that happens, I can move the cursor (first tap nearby to get rid of the selection, then tap+hold+drag) to where I want to add/modify the text and type as normal.

I have not been able to do this if the toot text is too short (e.g., <2 lines).

**Comment by jinsu35** [comment]
I think these issues are gone in the app version 1.4.10.

**Comment by JJKraw** [comment]
Yes, indeed. I can confirm what I wrote above is no longer happening. Excellent bug squashing!
