### ISSUE TITLE
[BUG] Post length is artificially limited by counting full length of url

### ISSUE THREAD

**Issue by jmeosbn** [mastodon/mastodon-ios#647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A post is artificially limited by counting full length of url; if I post on the web app instead there is no issue - as shown in the video

### Expected Behavior

URLs not to limit post as described 

### Environment

```markdown
- Device:iPhone 12
- OS: iOS
- Version:16.1
- Build:
```

**Comment by jmeosbn** [comment]
https://user-images.githubusercontent.com/530912/202892817-5d9deaea-dbcc-4de5-9100-c406865e610e.MOV

**Comment by jmeosbn** [comment]
I keep forgetting about this issue when trying to trim down posts to fit.

Here's an example of a post where I ended up with either 0 or 1 characters left.

I noticed I missed a character and went to edit it, wondering if I could even fit that character in.

However, this is how many characters I had left in the web version (since edit isn't yet in the app):

![image](https://user-images.githubusercontent.com/530912/203102251-b56beba4-98fa-4a4c-a94a-31e68602bb13.jpeg)

**Comment by j-f1** [comment]
Looking into this!

**Comment by FediVideos** [comment]
Is there any update on this? Just had someone point out this bug and it seems quite a major difference from the web experience.

This bug would promote the use of link shorteners, which would harm people's privacy.

**Comment by j-f1** [comment]
I opened #669 which should fix this issue, but it has not been merged yet.

**Comment by FediVideos** [comment]
Any idea when it might make it into the app?

**Comment by j-f1** [comment]
¯\\\_(ツ)\_/¯

**Comment by ambanmba** [comment]
Do we have an ETA on this?

**Comment by stefjow** [comment]
I’d also like to know..

**Comment by renchap** [comment]
Fixed by #1336, it will be in the next release.
