### ISSUE TITLE
[FEATURE] Allow changing profile header image

### ISSUE THREAD

**Issue by jmeosbn** [mastodon/mastodon-ios#649]
- [x] I have searched other issues

Currently, editing the profile shows the avatar image and bio info/links to be editable, but clicking the header image just displays it full screen.

### Expected

That header image could be changed, and cropping chosen/previewed so user could best make use of the image.

**Comment by kimar** [comment]
Hello @jmeosbn thank you for this feature request, [a PR containing this improvement](https://github.com/mastodon/mastodon-ios/pull/615) has already been merged to `develop` and will be shipped with the next release.

**Comment by jmeosbn** [comment]
Ah, that's great. Sorry, I searched issues but I'll try searching PRs too in future.

Is there a TestFlight I can join - I test and provide feedback to a few apps that way.

Many thanks!
