### ISSUE TITLE
[BUG] Treatment of carriage returns is strange/inconsistent with web app and and apps elsewhere

### ISSUE THREAD

**Issue by jmeosbn** [mastodon/mastodon-ios#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When making a post or editing a user’s bio, the app seems to render a carriage return as if it is a new paragraph (eg. two `<CR>` in most editors).

This is compounded by the line height being shown as extra tall.

Below you can see the cursor extends a long way below that expected, and the increased blank space between lines and (especially) paras.

![07BDE4F7-E779-49C5-8D45-EEFA3C221E54](https://user-images.githubusercontent.com/530912/202894358-ff10c396-ba4a-4c0e-95d2-ef540bc02577.jpeg)

This is most obvious when comparing the bio written within the mobile app, which shows the two paras, with the web, where it is just two lines.

![BB41CA3A-313E-4BF1-B9A0-D96B96628D47](https://user-images.githubusercontent.com/530912/202894467-a2fb7d05-53a8-4441-9b1f-23e17efc10cf.jpeg)

![E5C39C98-6AE6-4460-A4AA-D6DDFAF1B801](https://user-images.githubusercontent.com/530912/202894465-b80254f0-f409-4f2f-9633-8862b532a390.jpeg)

### Expected Behavior

That one `<CR>` be rendered as a new line.

That two `<CR>` be rendered as a new paragraph.

### Steps To Reproduce

This applies to posts as well (as shown above), but as an example.

1. Here is the raw text of the bio

        This is my software related account; for my general account, see the links.
        Interested in various programming/scripting

2. Observe that it shows as two paragraphs in the app

3. Compare with the web app, where it is two lines

### Environment

```markdown
- Device: iPhone 12
- OS: iOS
- Version: 16.1
- Build:
```

**Comment by jmeosbn** [comment]
Playing around with this, it seems somewhat inconsistent.

The intent was for two paragraphs, but even when you have two paragraphs to start with, editing to say, fix a typo (and not touching anything around the `<CR>`s) will remove the paragraph break so it’s again two lines.

You can see this happening before committing the edit, by putting the cursor at the start of the second line and backspacing once: It should now be two lines (instead of paras) but it's backspaced into the previous line.

**Comment by jmeosbn** [comment]
Note also, that despite the carriage returns between (actual) paragraphs looking too large in the post editor (looks almost like two blank lines), in the posted text, the viewed gap is fairly small.

Here is the editor:

![image](https://user-images.githubusercontent.com/530912/202895730-5288850c-1f62-47ed-baf9-467bfb0a331b.jpeg)

It almost looks like there's an unwanted `<CR>` between each para.

This post was actual made using the web app due to #647, and here's how the paragraphs are rendered there:

![image](https://user-images.githubusercontent.com/530912/202895810-e6f84e1a-0468-4c93-a85e-de19988927a0.jpeg)

Yet, despite the huge line spacing between paras in the app's post editor, in the rendered post there are smaller than expected or when compared to the above. The separation between individual paragraphs is barely there.

![image](https://user-images.githubusercontent.com/530912/202895847-1c85dde9-6586-44f6-8cce-dde27a65da09.jpeg)

**Comment by jmeosbn** [comment]
Just an addendum that, similar to how empty lines disappear (multiple `<CR>` collapsed into one?) when editing a bio, copying text from a post also strips empty lines.

**Comment by j-f1** [comment]
Related: https://github.com/mastodon/mastodon-ios/issues/554

**Comment by jmeosbn** [comment]
For completeness, here are the two Twitter and Mastodon editors with the same content.

![image](https://user-images.githubusercontent.com/530912/202901989-27a03829-ad6e-4eff-9912-c42e55c46346.jpeg)

![image](https://user-images.githubusercontent.com/530912/202901999-25bc7a0a-c4c4-405d-8e25-ce3eb73c2cbf.jpeg)

**Comment by jmeosbn** [comment]
I think the issue with the *display* of line height, is perhaps due to the text line height being increased to provide spacing between lines, rather than the setting for the line gap being increased to get the same effect.

This can be seen by the size of the cursor.

I think iOS adjusts* various things automatically – and probably has separate line and paragraph gap spacings – when the line gap is set larger to whatever it is now, and the line (cursor) height set smaller.

* I'm not a pro iOS dev so don't have the terminology to hand. 😉

**Comment by j-f1** [comment]
I believe this was fixed in #777.

**Comment by jmeosbn** [comment]
Yup! The paragraphs are a little tight but this is way better.

Would be nice to have a line height option but I expect that's waaay down the list.
