### ISSUE TITLE
[BUG] Sign Out from the app does not forget the user's authorization

### ISSUE THREAD

**Issue by 5ean5ullivan** [mastodon/mastodon-ios#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Logging out of the Mastodon app does not revoke authorization from Safari's cache. Therefore, **a password is not required** to sign back into the app. In other words, one is not forgotten when signing out of the app; the browser cache remembers. Uninstalling the app didn't revoke sign-in.

Edited to add: I tested again a few times with a clean browser cache. I typically use private mode and am not logged into any sites in Safari. Logging into the app does not log one into Mastodon also in Safari. But if one does login in via Safari it starts to get entangled. Logging out of Safari at that point seems to affect the behavior described above.

I feel that this is a potentially serious OPSEC issue for those whose device could be targeted when, for example, crossing a border. Such individuals need to be able to sign out of Mastodon reliably.

### Expected Behavior

Selecting "Sign Out" from the app will clear all authorizations so that a password is required to sign in to Mastodon.

### Steps To Reproduce

Sign Out.
Log in.
Enter your server.
Next.
Continue.
Authorize.

### Environment

```markdown
- Device:iPhone SE
- OS:16.1.1
- Version:1.4.7
- Build:199
```

### Anything else?

See this post for a video demonstration: https://infosec.exchange/@5ean5ullivan/109398524880037273

**Comment by redpola** [comment]
Probably related?: The login cached in the internal browser (“the boring zone”->”account settings”) can differ from that of the current mastodon user. I didn’t realise I was looking at the settings of an alt account because of this.
