### ISSUE TITLE
Can't switch accounts with VoiceOver on iOS

### ISSUE THREAD

**Issue by charadani** [mastodon/mastodon-ios#689]
First, congratulation on the owork you have done to make this app work with VoiceOver. It is overall very good.

I have tried to double tap where it says "Logo button" but nothing happens. Maybe there is a way for VoiceOver users to change accounts but it is not very apparent.

**Comment by j-f1** [comment]
There should be a hint on the fifth tab of the tab bar (“Profile”): “Double tap then hold to show account switcher.”

**Comment by charadani** [comment]
Thanks much.

Fair enough. I just had my hints disabled and did not realised. Will close this now.
