### ISSUE TITLE
Update documentation to make it clear the apps are a simplified experience 

### ISSUE THREAD

**Issue by SamStephens** [mastodon/mastodon-ios#698]
Based on a similar issue from Mastodon Android: https://github.com/mastodon/mastodon-android/issues/396

In discussion with @grishka about the Android app [I was told](https://github.com/mastodon/mastodon-android/issues/22#issuecomment-1321075092):

> This app is for new users. There are more advanced apps for more advanced users.
> [...]
> This app is for new users. The minimal feature set is purposeful.

The [Mastodon Android README.md states](https://github.com/mastodon/mastodon-android/blob/9facdb938d798e139b8da8bc9be6c7d344792ae8/README.md?plain=1#L12):

> [...] we work off of an internal roadmap and aim for feature-parity and consistency with our iOS app. The iOS app is designated as the "primary" between the two, therefore, if you want to request features, please do so in the [Mastodon for iOS](https://github.com/mastodon/mastodon-ios) repository.

If the Android application purposefully has a minimal feature set, and the Android app follows the iOS app, that implies the iOS app purposefully has a minimal feature set.

Please make this clear in the iOS store listing. Please make it clear in the README.md of this repository. Please consider renaming this application to something like Mastodon Basic/Mastodon Express/Mastodon Light to make it clear this is deliberately not the full experience. At the moment, I regularly see posts in my feed warning people away from the official apps, because people go to these apps expecting the full experience, and are disappointed when they do not provide that.

**Comment by Gargron** [comment]
>  Please consider renaming this application to something like Mastodon Basic/Mastodon Express/Mastodon Light

No, that is not going to happen.

> This app is for new users. The minimal feature set is purposeful.

The only purposefully omitted features are the federated timeline and the unlisted visibility setting.

**Comment by SamStephens** [comment]
> The only purposefully omitted features are the federated timeline and the unlisted visibility setting.

@Gargron then maybe tell **your own developers** to not tell us "the minimal feature set is purposeful."

Firstly, I had no idea there were **any** features being deliberately omitted. Then I was told the apps have a "minimal feature set". Now I'm being told there's only a couple of deliberately omitted features.

If you documented this stuff up front, if expectations were clearly set, you wouldn't have to waste your time with issues like this. And the users of your applications would know what to expect, and why and not be surprised and disappointed by the deliberate omissions from those apps.
