### ISSUE TITLE
[BUG] "Take Photo" file size is too big

### ISSUE THREAD

**Issue by jamespauly** [mastodon/mastodon-ios#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the native Mastodon App for iOS, using the option to take a picture in the app, the file is very large and will not upload due to the size of the file, however files in the photo album as automatically downsized so they can be uploaded.

### Expected Behavior

Should be able to take a photo in the app and have it downsized on the fly.

### Steps To Reproduce

1. Open the IOS app.
2. Create a new post.
3. Click the picture icon.
4. Chose "Take Photo".
5. Take a photo and it will not upload due to size.

### Environment

```markdown
- Device: iPhone 13
- OS: iOS 16.0
- Version: v1.4.7
- Build: 199
```

**Comment by j-f1** [comment]
This was fixed in https://github.com/mastodon/mastodon-ios/pull/674.
