### ISSUE TITLE
[BUG] attempting to upload a 54K image results in a 502 error on Mastodon for Mac

### ISSUE THREAD

**Issue by jayholler** [mastodon/mastodon-ios#712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="779" alt="Screenshot 2022-11-30 at 11 10 26 AM" src="https://user-images.githubusercontent.com/25752097/204853845-89ef93e3-14c1-43cf-a1e9-c1559377d973.png">
When attempting to attach an image to a reply, I'm consistently able to reproduce a 502 result. My instance is macaw.social.
The same action works fine on the Mastodon web client.

### Expected Behavior

I expected to attach the image and publish the post.

### Steps To Reproduce

1. Attach an image in Mastodon on Mac
2. Wait for the upload to fail
3. Observe the return code is a 502

### Environment

```markdown
- Device: M1 MacBook Air
- OS: macOS 13.0.1 (22A400)
- Version: Mastodon for iOS v1.4.7
- Build: (199)
```

### Anything else?

I've checked with the admins of macaw.social and they report that this is a common issue with folks using the Mastodon for iOS app, but we don't have any other clues as to why this fails when the web client works fine.

**Comment by jayholler** [comment]
Not sure what to make of this, but I was able to attach a different image with no issue. Attaching the image which worked in case it offers any clues. 
<img width="1255" alt="Screenshot 2022-11-30 at 12 16 34 PM" src="https://user-images.githubusercontent.com/25752097/204864897-4264dce6-70ab-4df3-b140-45a8d7e427c8.png">

**Comment by j-f1** [comment]
Can you use a tool like [Proxyman](https://proxyman.io) with SSL bypass enabled for your Mastodon server’s domain to record your attempt to post the image and then upload the raw request and response here so we can try to debug?

**Comment by jayholler** [comment]
I tried this, but of course now I cannot reproduce the issue! How frustrating. I tried multiple times to reproduce but every upload succeeds now...

**Comment by jayholler** [comment]
The latest version seems to have removed this intermittent issue.
