### ISSUE TITLE
[FEATURE] Open link in standard browser

### ISSUE THREAD

**Issue by blueturtleai** [mastodon/mastodon-ios#726]
If you tap on a link in a post, it is opened in Safari. Instead it should be opened in the configured standard browser, which is Brave in my case.

**Comment by j-f1** [comment]
If you go to your profile tab → Settings and enable “Use default browser to open links” that’s exactly what you’ll get.

**Comment by blueturtleai** [comment]
Perfect thanks. Perhaps it makes sense to make this the default 🤔?
