### ISSUE TITLE
Build for iOS 13

### ISSUE THREAD

**Issue by rodarima** [mastodon/mastodon-ios#737]
Hi,

Is there any strong dependency with iOS 14?, or can we lower the minimum requeriments to iOS 13? I'm stuck on 13.5.1 until I find a suitable Jailbreak update.

I don't have a Mac machine to try to patch and build it myself, but I can poke around with Darling and xcode tools on my Linux machine, if it doesn't require a large rewrite (not very familiar with Swift yet).

**Comment by zeitschlag** [comment]
We actually plan on supporting the last two most recent iOS-versions only, iOS 15+. This enables us to use more recent Swift/iOS-features and makes maintenance way easier. Also, after quickly checking, some of our dependenies require iOS 14+ :/
