### ISSUE TITLE
“Open in Safari” opens internal web view, not Safari

### ISSUE THREAD

**Issue by barijaona** [mastodon/mastodon-ios#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I look at a post in my timeline, I have an option to “Open in Safari” (“Ouvrir dans Safari” in french localization). 
When selected, it opens a webview, but I am still in the Mastodon for iOS app. 
I have to perform an extra step to really open the post in Safari : hit the Safari icon. 

### Expected Behavior

“Open in Safari” should bring directly to the Safari app, as the equivalent command in Metatext does. 
This is needed for consistency, and would allow the user to quickly get to the complete Safari environment (especially favorites/bookmarklets in my case). 

### Steps To Reproduce

As described above. 

### Environment

```markdown
- Device: iPhone SE (2nd generation), iPhone 14 Pro Max
- OS: iOS 16.1.1
- Version: 1.4.8
- Build: 219
```

### Anything else?

I have bookmarklets installed in my Safari: https://github.com/barijaona/mastodon-bookmarklet-generator

**Comment by kimar** [comment]
@barijaona in the Settings-Menu there is an option called "Use default browser to open Links" when this is enabled your links will open up in Safari.app, given it's set as your default browser.

![Simulator Screen Shot - iPhone 14 Pro - 2022-12-07 at 07 23 13](https://user-images.githubusercontent.com/126418/206104491-8ffce10a-5ab4-4f35-8096-5101b0469c39.png)

**Comment by barijaona** [comment]
So there is an inconsistency between the setting and the label in the Share menu.

When "Use default browser to open links" is set, the menu displays "Open in browser"
When it is unset, it displays "Open in Safari"

It should be the reverse situation. It should display "Open in browser" when the setting is off.

I think you should reopen the issue. I have checked that the problem is present in both English and French localizations.
