### ISSUE TITLE
Suggestion: Embed PeerTube videos on PeerTube posts

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon-ios#743]
If you boost a PeerTube post at the moment it just shows a link without the embedded video. If it is feasible and doesn't cause complications, it would be nice if the video itself could be embedded as it is a central part of PeerTube posts?

This is maybe different to YouTube links because the PeerTube posts are part of the Fediverse and replies to these posts appear in the comments section of the video when viewed on their original server.

**Comment by j-f1** [comment]
Just tested with #727 and the embed seems to work well including full screen and PiP with https://video.blender.org/w/jMQsH9XaaVs4CzkqnweVYy:

<img src=https://user-images.githubusercontent.com/25517624/206267512-04bb65c6-260f-4027-8f7d-3243b64c2746.png width=200> <img src=https://user-images.githubusercontent.com/25517624/206267618-e3588a00-e138-481b-a042-035c63631bc8.png width=200> <img src=https://user-images.githubusercontent.com/25517624/206267744-440435c7-f62d-4f79-a7b4-7a1fb1a2b5a3.png width=200>

**Comment by FediVideos** [comment]
Ooh that looks nice! Thank you for update!

Can't wait for this to be on the official app :)
