### ISSUE TITLE
[BUG] main feed tab forgets my place after visiting any other tab

### ISSUE THREAD

**Issue by jepyang** [mastodon/mastodon-ios#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I scroll down my main feed. When I switch to another tab (search or notifications or my profile) and then go back to my main feed, it has lost my place and gone back to the top.

### Expected Behavior

I would expect the main feed to remember where I was so that I can continue reading chronologically. This is especially annoying when I switch to another tab inadvertently (often switching to my profile by accidentally brushing my phones screen with the heel of my palm, for instance).

### Steps To Reproduce

Pretty much as described above.

1. scroll any distance through the main feed
2. Switch to any other tab
3. Return to main feed

### Environment

```markdown
- Device: iPhone 12
- OS: 15.6.1
- Version: 1.4.8
- Build: 219
```

### Anything else?

I am reasonably sure this behavior started with the most recent update. (The one that added hashtag-following)
(tried to attach screenshots but github borked them. Feel like it’s self-explanatory but if screenshots would help I’ll try again.)

**Comment by JJKraw** [comment]
Can confirm this behavior.

Device: iPhone SE 2 gen
OS: 16.1.2
Version 1.4.8
Build: 219

**Comment by C-Duv** [comment]
Same issue here.

Device: iPhone 7
iOS: 14.8.1
Version: 1.4.9
Build: 224

Note: The "bug" also happens when I load the application: I expect it to keep track of where I was in the main feed the last time I opened the application.

**Comment by jepyang** [comment]
Just want to bump this, as it is easily my most frustrating and most commonly-encountered bug with the software.

so this isn’t a totally useless bump, a couple workarounds I’ve figured out:
- if you open a specific toot and switch tabs, when you switch back to home tab, you’ll still be on the toot you opened. Swipe back to the timeline and your spot will be saved still.
- If you forget to “save” your spot using the above method, if you’re quick you can tap the “mastodon” word at the top of the feed and it’ll scroll you back down to your last spot. You have to be quick though, if it auto-loads new posts, it will take you to the new top of the feed instead of your old spot.

hope the proposed code fix from above can be incorporated into the next App Store release!

**Comment by j-f1** [comment]
- Linking the PR again: https://github.com/mastodon/mastodon-ios/pull/841
