### ISSUE TITLE
[Feature Request] Censorship resistance (DoH and SNI mask?)

### ISSUE THREAD

**Issue by iceBear67** [mastodon/mastodon-ios#747]
According to the contributing guide, I have to post it here again.

From [mastodon-android#451](https://github.com/mastodon/mastodon-android/issues/451)

_The Internet is under heavy censorship in some countries (China for example). To deal with it, some mastodon instances run behind an unblocked CDN service like Cloudflare._

_However, the authorities also pollute DNS responses in order to block those instances. Therefore, a mastodon client that supports DNS-Over-HTTPS or DNSCrypt can help people who are under censorship access those instances easier._

**Comment by j-f1** [comment]
It seems like this is more of a system level thing, since the app uses the built in networking APIs. All supported iOS versions support DNS over HTTPS so I think it would make sense to have folks set it up that way rather than having the app bundle its own network stack.

**Comment by iceBear67** [comment]
I got some progress on the Android one, but I don't know a lot about iOS programming.

Maybe it is only possible for Android?
