### ISSUE TITLE
[IMPROVEMENT] German translation for "Following" label in Profile view is weird

### ISSUE THREAD

**Issue by d4l-w4r** [mastodon/mastodon-ios#752]
Currently the label for the count of users a profile is following is translated as "Folge ich", which literally means "I follow". 
For the current users own profile page this is fine, but the same string is also used for other profiles, which looks a bit weird to me. 
For other profiles the correct string should read "folgt", which literally translates to "follows".

I feel like there's 3 Options:
1. Just don't translate and use the english "Following", as the "Follower" label is also not translated.
2. Use the non-personal form "Folgend"
3. Make a quick check for isSelf when the profile page loads and display different labels depending on whether it is the users own profile or another profile. 

Option 3 would be my preferred option, because it would result in the most clear and readable label (in my opinion).
Option 2 would feel like a regression, because that's how it used to be a while ago and it was horrible readability wise. Because Following was "folgend" and Follower was "folgende" and "following" can be translated to both folgend and folgende depending on context I always stumbled and wasn't sure what list I was looking at :D

If you think this is worthwhile and I don't receive pushback from fellow german speakers here, I will open another issue on the mastodon-android project and provide a PR for the implementation of Option 3 for Android. 
I can also try to provide the code for iOS.

The only thing I would need help with is the exact process of how to add a new key to the strings file and correctly get it into Crowdin.

In the end I think this could be an improvement for other languages as well where the current non-personal form is not as clear as the english "Following"/"Follower".

**Comment by j-f1** [comment]
Check out https://github.com/mastodon/mastodon-ios/pull/753

**Comment by d4l-w4r** [comment]
Oh cool! :)
Hang on I'll check if you caught all occurences...
I'm implementing this for Android right now and found 2 places where it needs to be changed. 
1. On the profile page
<img width="288" alt="Bildschirmfoto 2022-12-13 um 16 31 47" src="https://user-images.githubusercontent.com/4370186/207376074-ee38585d-ee56-4f59-9485-6ccceaadd90f.png">

2. In the header of the list of followers
<img width="288" alt="Bildschirmfoto 2022-12-13 um 16 32 32" src="https://user-images.githubusercontent.com/4370186/207376083-334c3c92-9b91-4fee-96cf-08dbddb0d0e4.png">

**Comment by j-f1** [comment]
I’ve currently updated:

- profile pages (your first screenshot)
- profile cards (search → For You)

I haven’t done anything for your second screenshot which uses a different set of strings entirely (`scene.following.title` vs `scene.profile.dashboard.following`) but also that UI needs some improvements (for example it just has “following” in lowercase in the title bar when something like the Android version with username/display name + “# following” would make more sense)

**Comment by d4l-w4r** [comment]
Ah okay that makes sense then. I only now the Android UI, because I don't have an iPhone available.
But if the UI from the second screenshot needs other improvements anyway, maybe it's for another commit.

So I will create an issue and PR for the android project and link it to this one :)
The actual content of the translated strings is then discussed over on crowdin, correct?

**Comment by j-f1** [comment]
I believe so! The iOS PR will wipe out the existing strings so folks will have a chance to make better ones for each language (not sure how to provide context if that’s possible)

**Comment by j-f1** [comment]
Following up, the related PR has been merged so you can update the translations whenever you’re ready (if you haven’t already) and they will go out in the next update.

**Comment by j-f1** [comment]
I believe this can be closed now.

**Comment by d4l-w4r** [comment]
Oh man, sorry! I completely forgot about this thread 🙈
An I never ended up making the necessary translation changes. 
Thanks for the reminder, I'll get on that! And yes this issue can be closed.
Thanks again for your work :)
