### ISSUE TITLE
iOS app uses a non-standard tab bar at bottom

### ISSUE THREAD

**Issue by Scenario** [mastodon/mastodon-ios#755]
### Steps to reproduce the problem

Look at this mess.
1. You can’t tell which tab is selected because…
2. The middle tab is actually a momentary button that entices you to tap it even when you don’t want to post.
3. The Notifications tab item doesn’t use the standard iOS badge. Just a tiny little dot that doesn’t show you the number of unread items.
4. The rightmost element is a custom control that should be up in the navigation bar or on a Settings screen, not in a tab bar. As is, tapping the up/down arrows with a single account does nothing but make that button blink. And that’s broken UI.

![1ACC11DA-FE5D-47E6-8250-7E7E9E83F5D7](https://user-images.githubusercontent.com/752155/207448157-06ae74f6-ff2d-4bbf-a5ef-6e68b61ce0db.jpeg)

### Expected behaviour

Use UITabBar

### Actual behaviour

Not using iOS UI elements

### Detailed description

This is unacceptable UI for those of us who bought into iOS for a familiar, consistent UX. It’s arguably a violation of Apple’s HIG.

### Specifications

Latest iOS app

**Comment by Der-K-2000** [comment]
Wrong repository → https://github.com/mastodon/mastodon-ios

**Comment by kimar** [comment]
I'm going to close this issue as there has been made a conscious design decision about this functionality and there are no plans to change this at the time being.
