### ISSUE TITLE
iOS English localization is showing UK spellings

### ISSUE THREAD

**Issue by Scenario** [mastodon/mastodon-ios#757]
### Steps to reproduce the problem

Look at Notifications in the iOS app. One or more English words aren’t localized properly.

### Expected behaviour

“favorited”

### Actual behaviour

“favourited”

### Specifications

Latest iOS app.

**Comment by Der-K-2000** [comment]
Wrong repository → https://github.com/mastodon/mastodon-ios

**Comment by zeitschlag** [comment]
Please head over to [Crowdin](https://crowdin.com/project/mastodon-for-ios) to suggest changes. Thank you!
