### ISSUE TITLE
The “:verified:” suffix is ugly AF

### ISSUE THREAD

**Issue by Scenario** [mastodon/mastodon-ios#765]
### Steps to reproduce the problem

Browse your timeline until you see a username followed by “:verified:”.

### Expected behaviour

A nice icon like a checkmark

### Actual behaviour

Ugly text

### Detailed description

This is what happens when nuts & bolts Engineers do UI work without supervision. ;)

### Specifications

Latest iOS app

**Comment by nightpool** [comment]
@Scenario Please stop filing these bugs in the wrong repository. We can transfer existing bugs, so you shouldn't recreate them, but please file new bugs at https://github.com/mastodon/mastodon-ios/issues

**Comment by j-f1** [comment]
Unable to reproduce:

![image](https://user-images.githubusercontent.com/25517624/207473601-1553fef9-b9e3-49af-be03-c54823f4219f.jpeg)

**Comment by Gargron** [comment]
> This is what happens when nuts & bolts Engineers do UI work without supervision. ;)

You have no right to insult people who work on this software provided to you free of charge and without any warranty.
