### ISSUE TITLE
Non-standard buttons everywhere?

### ISSUE THREAD

**Issue by Scenario** [mastodon/mastodon-ios#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Look at this big black button, sticking out like a sore thumb: ![6DB2EFD4-45C9-4237-8E87-9C3017337D93](https://user-images.githubusercontent.com/752155/207476403-c178f7d1-cbec-440b-b278-abb4bb156db0.jpeg)

### Expected Behavior

All UI elements should be standard UIKit controls. There is no reason and no excuse to use custom buttons for common actions. UIButton, for example, not only works just fine but it behaves properly under a variety of iOS appearance and accessibility modes.

### Steps To Reproduce

Look at any big black or big blue button in the iOS app. 

### Environment

```markdown
- Device:iPhone 11 Pro
- OS:latest
- Version:latest
- Build:latest
```

### Anything else?

Here, some rookie Designer probably thought the default/primary button needed extra emphasis. But UIButton already has a parameter for the “Done” style. There’s no reason to assume you’re smarter than Apple’s Usabilty team in this case. Save the gratuitous design statements for content areas, not our user interface. 👍🏻

**Comment by Gargron** [comment]
> Here, some rookie Designer probably thought

This is out of line. You are no longer welcome on our repositories.
