### ISSUE TITLE
Multiple accounts on same server not possible

### ISSUE THREAD

**Issue by rvlak** [mastodon/mastodon-ios#776]
If I try to add a second account that resides on the same server (e.g. mastodon.social), the iOS app automatically signs me in with the credentials of the first account. Ie there is no way to use two different accounts (personal + business) that are hosted on the same server and switch between them. The problem does not occur with accounts that are on different servers.

![91316C8C-84E8-44CE-8263-0C3451E64B10](https://user-images.githubusercontent.com/16000518/208032631-d6d1f387-a80c-40e8-94b3-fc8b17226433.png)![8113DE6B-AE44-468F-AE4C-ADC5913A04F3](https://user-images.githubusercontent.com/16000518/208032620-8362698b-9da1-4b74-b1fc-5d5ce63306c8.png)
![63A4CB94-ACB5-4F82-B5F6-7968E8F2881B](https://user-images.githubusercontent.com/16000518/208032639-fd196373-a4b3-4fba-a17c-cc13501ecbac.png)

**Comment by j-f1** [comment]
You should be able to sign out using the button in the top right corner of the web page and then sign back in with your second account. That said there might be other bugs there.

**Comment by rvlak** [comment]
Hi @j-f1 Thanks, that worked!
