### ISSUE TITLE
Clicking on a profile name should take you to the profile page

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon-ios#779]
At the moment, clicking on the name of the person who posted a message does nothing.

Clicking on a name should take you to their profile. (I realise clicking the profile picture works, but the name should work too as this is how the web interface and third party apps behave.)

I've just had to explain to new people that the name doesn't work on the official app, they assumed there was no way to see someone's profile except searching. Allowing people to click on names would avoid this confusion.

**Comment by j-f1** [comment]
Duplicate of #560

**Comment by FediVideos** [comment]
Closing as duplicate
