### ISSUE TITLE
[BUG] Filter titles not displayed in feed

### ISSUE THREAD

**Issue by ingernet** [mastodon/mastodon-ios#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As I scroll through the feed, filtered posts are displayed but replaced with a single word: “Filtered.” (The divs are also giant, but I believe there’s an enhancement request open for that.)

![8EFE0599-57CD-47C6-A08E-D99CD1B25B35](https://user-images.githubusercontent.com/6075258/208473054-efa88c4f-52b3-4de0-98fe-20e8d54c3bea.jpeg)

### Expected Behavior

The account settings tell me that the name of the filter is supposed to be included in the display:
![7105E801-2A67-4F2A-8921-EAB17F2BA459](https://user-images.githubusercontent.com/6075258/208473453-e436679d-c0e7-4931-9f6f-fc6d778fec08.jpeg)

### Steps To Reproduce

1. In Mastodon’s account settings, set up a filter called “test filter” and add a common word like `#introduction` choose “hide with warning”
2. Scroll through your feed in the app and notice that the filtered posts don’t have the “test filter” title displayed. (Also adding reference pic of what it looks like on the Mastodon site)

![838622AC-2977-4C0C-AA44-08204376E0F2](https://user-images.githubusercontent.com/6075258/208474310-2ae5b5f4-b42a-49d6-9fad-e7dd8502c709.jpeg)

### Environment

```markdown
- Device: iPhone SE gen 3
- OS: iOS 15.6.1
- Version: 1.4.8
- Build: 219
```

### Anything else?

This is on mindly.social, which is running Mastodon v4.0.2

**Comment by haugenhus** [comment]
This is a significant detriment to user experience. I want to be able to see which filter(s) is responsible to help me decide if I want to read the content anyway.

![image](https://github.com/mastodon/mastodon-ios/assets/73085536/9dc67919-dca2-47df-b381-dadc7ecc1297)
