### ISSUE TITLE
[Suggestion] App Widget

### ISSUE THREAD

**Issue by fegerar** [mastodon/mastodon-ios#807]
It would be cool to implement a widget that shows hashtags post trending.

**Comment by dnet890** [comment]
yeah, it will be great if we can see each our instance in the widget

**Comment by j-f1** [comment]
It looks like it’s currently “In Progress” on the public roadmap: https://joinmastodon.org/roadmap (IOS-37)

**Comment by zeitschlag** [comment]
Implemented in #993
