### ISSUE TITLE
[BUG] Compose button is always highlighted

### ISSUE THREAD

**Issue by moenodedev** [mastodon/mastodon-ios#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The compose button in the tab bar is highlighted.

![screenshot](https://user-images.githubusercontent.com/113457600/209333960-d84b3903-4c89-4e87-97f0-1203ffb35753.jpg)

### Expected Behavior

The compose button in the tab bar should not be highlighted.

### Environment

```markdown
- Device: iPhone
- OS: iOS 16.2
- Version: v1.4.8
- Build: 219
```

**Comment by zeitschlag** [comment]
Hello @moenodedev thank you for filing this issue. By "highlighted" you mean the background of the compose-button in the center of the tabbar, right?

**Comment by moenodedev** [comment]
Yes the button looks selected and can be distracting.

**Comment by moenodedev** [comment]
We can close this issue. I'm going to use Ivory since the UX is familiar.
