### ISSUE TITLE
[Feature]:  Set default server 

### ISSUE THREAD

**Issue by gr8rehanna** [mastodon/mastodon-ios#886]
### Description

Hi.
I have a local instance for friends and family only.\
When a user installs Mastodon Android or iOS app.\
On splash we have LOGIN : CREATE AN ACCOUNT.

Now user clicks either of these user is taken to server selection screen.\
My instance is not shown in suggestions list they gaveup and ask me WHAT TO DO.

#### What i am looking for.

When a user opens app.\
user will get 2 potions Login or signup.\
User clicks on LOGIN and should be taken to authorisation page of my own instance at xxx.com instead of SERVER SELECTION.

Same for SIGNUP (CREATE AN ACCOUNT)

### Suggested Solution

In configuration set variable to. \
server_dialogue=false ( to hide server selection)
node_url ( instance url i.e xxx.com 

#### WHY

As i mentioned earlier my instance is family only and has no public appearance.

Most of users are not used to Mastodon.
They dont see xxx.com (my instance) in suggestions and they just uninstall app or ask me which instance to choose.

**Comment by gr8rehanna** [comment]
Here is same comment not replied yet.
https://github.com/mastodon/mastodon-android/issues/447#issue-1486662984

**Comment by j-f1** [comment]
Are you planning to distribute the app yourself? Then you should be able to rebuild it by moving the code from [`MastodonLoginViewController.login`](https://github.com/mastodon/mastodon-ios/blob/8e7d11594402823c8ecf11695df96366ab3be8ac/Mastodon/Scene/Onboarding/Login/MastodonLoginViewController.swift#L130) to [`WelcomeViewController.signInButtonDidClicked`](https://github.com/mastodon/mastodon-ios/blob/8e7d11594402823c8ecf11695df96366ab3be8ac/Mastodon/Scene/Onboarding/Welcome/WelcomeViewController.swift#L259).

If you’re talking about tapping the “install iOS app” link(s) on the Mastodon web UI, it unfortunately seems like there isn’t a good way to directly send information to a native app directly after the user installs it.

A couple of options that might make sense:

- adding a `joinmastodon://login/mastodon.example` route to the app which would open the login UI for that domain, then add a new account when the login succeeds. (This would require tapping a second link to open the app again once it’s been installed)
- use an App Clip (this is on the [public roadmap](https://joinmastodon.org/roadmap) as IOS-42)
- configuring a Universal Link on `joinmastodon.org` (such as `/ios-app?server=mastodon.example`) which could present a variety of official and third-party Mastodon clients, and would be automatically handled by the official app if it is installed.

**Comment by gr8rehanna** [comment]
Thanks.\
Definitely what i was asking.

ps: I am not asking for install app links or login from web.

I am natively talking about apps.

E.g: User doesn't open browser just installs app from store or Android store (custom) rebuilt.

After installing app on phone user should simply click on login button and Default server should be picked automatically (configured mastodon url in config.file)

For ios first method looks good.

What about android?\
In manifest file if we change logon activity instead of splash?

or 

replace instance activity with own Mastodon logn page?

How is that supposed to work?\
Its about android app.

Thanks

**Comment by j-f1** [comment]
I don’t know anything about the Android codebase, unfortunately. (but maybe someone else will chime in?)

**Comment by gr8rehanna** [comment]
Thanks .

Unfortunately all issues are open & seems no one is thr to answer.

Btw thanks again.

**Comment by zeitschlag** [comment]
Have you tried entering your domain on the Login-screen? What happens then?

**Comment by gr8rehanna** [comment]
> @gr8rehanna Have you tried entering your domain on the Login-screen? What happens then?

I tried ones but it did not worked. 
So i planned not to mess with app for now. 

I someone mamaged to run a powerful server, & seems mastodon is now growing..

**Comment by BrunoFenzl** [comment]
I am also interested in this. I am building a mastodon instance for all my street neighbors and users should only be able to sign-up/login to our specific server, so the view to choose an instance will be bypassed/removed. The resulting iOS app will be distributed in the app store under a different name.
