### ISSUE TITLE
Action extension can open the wrong user

### ISSUE THREAD

**Issue by j-f1** [mastodon/mastodon-ios#897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to open https://ruby.social/@katei using the action extension, I am directed to https://scholar.social/@kateiyas instead. Searching for that user directly from the search input (by @name@domain or URL) works fine.

### Expected Behavior

The profile https://ruby.social/@katei should be opened.

### Steps To Reproduce

1. Open https://ruby.social/@katei in Safari
2. Tap share → Open using Mastodon

### Environment

```markdown
- Device: iPhone 13 Pro
- OS: iOS 16.3
- Version: recent `develop`
```

**Comment by Gargron** [comment]
Is this after #888? I would imagine the described behaviour could refer to what was before that PR.

**Comment by j-f1** [comment]
Yep, that seems to have fixed it!
