### ISSUE TITLE
[BUG] Search doesn't search for #hashtags

### ISSUE THREAD

**Issue by supernovae** [mastodon/mastodon-ios#913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

* Open Mastodon for iOS.

* Click Search glass

* Type "#hiking" (putting on quotes because github is trying to shortcode the hashtag - remove quotes to try on app)

Only hashtags return.  You can click on a hashtag, but i'd expect with the pivot you should be able to click on posts and see posts with that hashtag in it.

![20230130_213807000_iOS](https://user-images.githubusercontent.com/1461719/215608338-328d3bce-25f8-4840-a27e-ba31269408e2.png)

### Expected Behavior

* Open Mastodon for iOS
* Click Search
* Type in your  # hashtag
* See hashtags, head to pivot page, see posts with hashtags in it.

For example, the experience in Ivory works this way. Screenshots below

Click search icon, type # hiking and hit enter and you see posts tagged with hiking hashtag

![20230130_221038000_iOS](https://user-images.githubusercontent.com/1461719/215608502-5ad9f7af-06c7-482f-b47a-83936a5a6974.png)

![20230130_214039000_iOS](https://user-images.githubusercontent.com/1461719/215608520-725cdaa8-c4ab-4a2b-8596-3108a7b7826a.png)

### Steps To Reproduce

Download iOS App
Click Search glass
type # hashtag to search for

Hashtags show up but pivot to posts and there are no posts - seems expected behavior is to drill down through hashtags and see posts but seems like a bug you can't pivot

### Environment

```markdown
- Device: iphone 11
- OS:15
- Version:1.4.9
- Build: 224
```

**Comment by j-f1** [comment]
For reference, the app’s behavior matches the search field on the official site — if you select “posts” there are no results

**Comment by supernovae** [comment]
I'd say the behavior is broken on the official website too. I created an issue to show here: 

https://github.com/mastodon/mastodon/issues/23323

I'd expect i want to find "@person" as much as i want to find posts from @person  

And I'd like to find hashtags that include my hashtag as well as posts that include my hashtag.

**Comment by TazzerMAN** [comment]
Same here

**Comment by nielsle** [comment]
It would be great to find a top 50 list of accounts that have posted a given hashtag within the last month.

If you search for the hashtag #nba, then most of the posts are made by a few very active bots. These bots are fine, but if you want to create a community, the you also need to highlight posts that were not  posted by bots.
