### ISSUE TITLE
Follow button is not visible in ipadOS in landscape mode

### ISSUE THREAD

**Issue by fotensity** [mastodon/mastodon-ios#962]
pick any hashtag, the follow burton shows up on the right. turn the ipad in landscape mode, follow button is not visible any more.

**Comment by fotensity** [comment]
![image](https://user-images.githubusercontent.com/6478261/222326360-bf66d5bd-a127-4d92-9c7a-b293fa771f75.jpeg)

![image](https://user-images.githubusercontent.com/6478261/222326394-68098d25-e312-4c6e-893b-150949437df2.jpeg)

**Comment by zeitschlag** [comment]
Duplicate of #657
